# -*- coding: utf-8 -*-
import urllib.parse

def gmaps(addr):
    return "https://www.google.com/maps/search/?api=1&query=" + urllib.parse.quote(addr)

GENERIC_AMENITY_NOTE = (
    "Техника отдельным списком не указана — вьетнамские объявления обычно пишут просто "
    "«đầy đủ nội thất» (полностью меблировано). На практике в такую меблировку почти всегда "
    "входят кондиционер, холодильник, кровать и шкаф; стиральная машина — не всегда своя, "
    "иногда общая на этаж; сушильной машины и отдельного рабочего места в объявлениях почти "
    "никогда нет. Точный список уточняйте у хозяина при контакте."
)

# =========================================================================
# Nha Trang apartments 6-9 млн ₫/мес, разбито по источникам, актуально на 15.08.2026
# =========================================================================
CHOTOT = [
    dict(price="6,0 млн ₫/мес", area="40 м²", district="Phước Hải (юг)",
         title="Cho thuê căn 1 phòng ngủ riêng — Hà Quang 2",
         address="Hà Quang 2, Phường Phước Hải, Nha Trang",
         phone="только через чат на странице (Hiện SĐT)",
         desc="Полная меблировка, 1 отдельная спальня.", amenity_note=GENERIC_AMENITY_NOTE,
         url="https://www.nhatot.com/thue-can-ho-chung-cu-thanh-pho-nha-trang-khanh-hoa/134095066.htm"),
    dict(price="6,0 млн ₫/мес", area="30 м²", district="Phước Long (юг)",
         title="Cho thuê căn hộ Phước Long — Đường Lê Hồng Phong",
         address="Lê Hồng Phong, Phường Phước Long, Nha Trang",
         phone="086 676 ** (полностью — кнопка «Hiện SĐT» на странице)",
         desc="Студия, полная мебель, район с развитой инфраструктурой и хорошей охраной. Депозит 1 мес., электричество 4,5 тыс ₫/кВт·ч, вода 150 тыс ₫/чел., договор на 1 год.",
         amenity_note=GENERIC_AMENITY_NOTE,
         url="https://www.nhatot.com/thue-can-ho-chung-cu-thanh-pho-nha-trang-khanh-hoa/133700375.htm"),
    dict(price="6,5 млн ₫/мес", area="50 м²", district="Phước Long (юг)",
         title="Меблированная квартира",
         address="Phước Long, Nha Trang",
         phone="только через чат на странице (Hiện SĐT)",
         desc="Полная мебель, район Phước Long.", amenity_note=GENERIC_AMENITY_NOTE,
         url="https://www.nhatot.com/thue-can-ho-chung-cu-thanh-pho-nha-trang-khanh-hoa/134094975.htm"),
    dict(price="7,0 млн ₫/мес", area="30 м²", district="Tân Lập (центр)",
         title="Квартира в центре, рядом рынок Xóm Mới",
         address="8A Ngô Thời Nhiệm, Phường Tân Lập, Nha Trang",
         phone="+84 33 242 1792 (Zalo/WhatsApp/Telegram)",
         desc="6 этаж, свободный график, управление прямо в здании. Электричество 4 500 ₫/кВт·ч, вода 150 000 ₫/чел., прочие сборы 200 000 ₫/комната. Без животных, электроскутеров и грудных детей.",
         amenity_note=GENERIC_AMENITY_NOTE,
         url="https://www.nhatot.com/thue-can-ho-chung-cu-thanh-pho-nha-trang-khanh-hoa/133965062.htm"),
    dict(price="7,0 млн ₫/мес", area="40 м²", district="Phước Hải (юг)",
         title="Студия повышенной комфортности — Lê Hồng Phong",
         address="985 Lê Hồng Phong, Phường Phước Hải, Nha Trang (напротив заправки)",
         phone="+84 33 242 1792 (Zalo/Telegram/WhatsApp/KakaoTalk)",
         desc="Камеры 24/7, замок по отпечатку пальца, лифт до этажа, звукоизоляция, полная ПРЕМИАЛЬНАЯ мебель, скоростной интернет. Электричество 5 000 ₫/кВт·ч, вода 150 000 ₫/чел., прочее 200 000 ₫/комната. Без электроскутеров и грудных детей, животные разрешены.",
         amenity_note="Заявлена «премиальная» меблировка (выше среднего), но конкретный список техники не дан — см. общее примечание в конце раздела.",
         url="https://www.nhatot.com/thue-can-ho-chung-cu-thanh-pho-nha-trang-khanh-hoa/133988450.htm"),
    dict(price="7,0 млн ₫/мес", area="40 м²", district="Vĩnh Phước (север)",
         title="Меблированная квартира",
         address="Vĩnh Phước, Nha Trang",
         phone="только через чат на странице (Hiện SĐT)",
         desc="Полная мебель, район Vĩnh Phước на севере города.", amenity_note=GENERIC_AMENITY_NOTE,
         url="https://www.nhatot.com/thue-can-ho-chung-cu-thanh-pho-nha-trang-khanh-hoa/133984854.htm"),
    dict(price="7,5 млн ₫/мес", area="40 м²", district="Phước Hòa (центр-запад)",
         title="Студия с балконом, ул. Lam Sơn",
         address="Lam Sơn, Phường Phước Hòa, Nha Trang",
         phone="только через чат на странице (Hiện SĐT)",
         desc="Полная мебель, есть балкон.", amenity_note=GENERIC_AMENITY_NOTE,
         url="https://www.nhatot.com/thue-can-ho-chung-cu-thanh-pho-nha-trang-khanh-hoa/134094877.htm"),
    dict(price="7,5 млн ₫/мес", area="55 м²", district="Phương Sơn (запад)",
         title="Современная студия, ул. 23/10",
         address="23/10, Phường Phương Sơn, Nha Trang",
         phone="+84 834 598 183 — Тиен (Zalo/WhatsApp, Telegram @Tientmw)",
         desc="Рядом школы/больница/ТЦ, охраняемый район. 1 санузел, ОТДЕЛЬНАЯ ПОСТИРОЧНАЯ (phòng giặt riêng), лифт, 2 этаж, свободный график. Электричество 5 000 ₫/кВт·ч, вода 20 000 ₫/м³. Депозит 1 мес., договор 3–6 мес.",
         amenity_note="✓ Стиральная машина/постирочная — упомянута явно («phòng giặt riêng»). Остальное (сушилка, кухня, кондиционер, холодильник, рабочее место) отдельно не перечислено.",
         url="https://www.nhatot.com/thue-can-ho-chung-cu-thanh-pho-nha-trang-khanh-hoa/133609077.htm"),
    dict(price="8,5 млн ₫/мес", area="65 м²", district="Vĩnh Trường (юг)",
         title="Меблированная квартира",
         address="Vĩnh Trường, Nha Trang",
         phone="только через чат на странице (Hiện SĐT)",
         desc="Полная мебель, южная часть города.", amenity_note=GENERIC_AMENITY_NOTE,
         url="https://www.nhatot.com/thue-can-ho-chung-cu-thanh-pho-nha-trang-khanh-hoa/133992753.htm"),
    dict(price="8,8 млн ₫/мес", area="45 м²", district="Phước Hòa (центр-запад)",
         title="Студия с балконом, ул. Lam Sơn (вариант побольше)",
         address="Lam Sơn, Phường Phước Hòa, Nha Trang",
         phone="только через чат на странице (Hiện SĐT)",
         desc="Полная мебель, балкон.", amenity_note=GENERIC_AMENITY_NOTE,
         url="https://www.nhatot.com/thue-can-ho-chung-cu-thanh-pho-nha-trang-khanh-hoa/134094699.htm"),
    dict(price="8,9 млн ₫/мес (в тексте объявления — 8,5)", area="48 м²", district="Vĩnh Hòa (север)",
         title="1-спальная, разрешены животные и электроскутеры",
         address="52 Phạm Ngọc Thạch, Phường Vĩnh Hòa, Nha Trang",
         phone="096 741 ** (полностью — кнопка «Hiện SĐT»)",
         desc="Большой балкон, полная мебель, СТИРКА И СУШКА ПРЯМО В КОМНАТЕ (giặt phơi tại phòng). Депозит 5 млн (оплата за 1 мес.). Электричество 4 500 ₫/кВт·ч, вода 150 000 ₫/чел., интернет+мусор 150 000 ₫/комната, генеральная уборка 150 000 ₫/раз.",
         amenity_note="✓ Стиральная машина — есть, стирка и сушка (на верёвке, не машинная) прямо в комнате. Кухня/кондиционер/холодильник/рабочее место отдельно не перечислены.",
         url="https://www.nhatot.com/thue-can-ho-chung-cu-thanh-pho-nha-trang-khanh-hoa/133831778.htm"),
    dict(price="9,0 млн ₫/мес", area="68 м²", district="Phương Sơn (запад)",
         title="1-спальная, современный дизайн, ул. 23/10",
         address="23/10, Phường Phương Sơn, Nha Trang",
         phone="+84 834 598 183 — Тиен (Zalo/WhatsApp, Telegram @Tientmw)",
         desc="Угловая квартира, электронный замок, ЦЕНТРАЛИЗОВАННЫЙ ВОДОНАГРЕВАТЕЛЬ (nóng lạnh hecbum). Электричество 5 000 ₫/кВт·ч, вода 20 000 ₫/м³. Депозит 1 мес.",
         amenity_note=GENERIC_AMENITY_NOTE,
         url="https://www.nhatot.com/thue-can-ho-chung-cu-thanh-pho-nha-trang-khanh-hoa/132198573.htm"),
    dict(price="9,0 млн ₫/мес", area="55 м²", district="Vĩnh Hòa (север)",
         title="2-спальная, ЖК Hoàng Quân (HQC), заселение 20.08",
         address="Trần Quang Diệu, Phường Vĩnh Hòa, Nha Trang",
         phone="037 741 ** (полностью — кнопка «Hiện SĐT»)",
         desc="4 этаж, 800 м до моря, 2 спальни/2 санузла, гостиная, балкон и лоджия, полная мебель. Долгосрочный договор, депозит 2 мес. (оплата за 1).",
         amenity_note=GENERIC_AMENITY_NOTE,
         url="https://www.nhatot.com/thue-can-ho-chung-cu-thanh-pho-nha-trang-khanh-hoa/133917382.htm"),
]

BATDONGSAN = [
    dict(price="6,0 млн ₫/мес", area="52 м², 2 спальни, 1 с/у", district="Vĩnh Phước (Бак Нячанг)",
         title="Квартира с видом, ул. 2/4, этаж 2, комн. D2.2",
         address="Đường 2/4, Phường Vĩnh Phước, Nha Trang",
         phone="0989 271 *** (полностью — кнопка «Hiện số» или Zalo-чат на странице), брокер Lê Tài",
         desc="На фото видна отдельная кухня со встроенными шкафами и мойкой.",
         amenity_note="✓ Кухня видна на фото (кухонный гарнитур, мойка). Остальная техника (стиралка/сушилка/кондиционер/холодильник/рабочее место) не расписана текстом — смотрите полную галерею из 8 фото по ссылке.",
         url="https://batdongsan.com.vn/cho-thue-can-ho-chung-cu-duong-2-4-phuong-vinh-phuoc-350/cho-2-4-gia-4-trieu-52-m2-2-pn-view-dep-pr41413787"),
    dict(price="6,0 млн ₫/мес", area="51 м², 2 спальни, 2 с/у", district="X. Vĩnh Hiệp (Тай Нячанг)",
         title="CT6 Vĩnh Điềm Trung, базовая мебель",
         address="Khu đô thị Vĩnh Điềm Trung, Xã Vĩnh Hiệp, Nha Trang",
         phone="через Zalo-чат/звонок на странице объявления",
         desc="Указано «nội thất cơ bản» — базовая, НЕ полная меблировка (в отличие от большинства других вариантов в подборке).",
         amenity_note="⚠️ Меблировка базовая, не полная — уточняйте, что именно входит, это единственный вариант в подборке с такой пометкой.",
         url="https://batdongsan.com.vn/cho-thue-can-ho-chung-cu-xa-vinh-hiep-1-khu-do-thi-vinh-diem-trung/cho-ct6-iem-tay-nha-trang-51m2-2pn-6tr-thang-noi-that-co-ban-pr46183236"),
    dict(price="7,0 млн ₫/мес", area="67 м², 2 спальни, 1 с/у", district="Phước Long (Нам Нячанг)",
         title="Chung cư XH1 VCN Phước Long",
         address="Khu đô thị VCN Phước Long, Phường Phước Long, Nha Trang",
         phone="через Zalo-чат/звонок на странице объявления",
         desc="Комплекс XH1 VCN Phước Long, обновлено 15.08.2026.",
         amenity_note=GENERIC_AMENITY_NOTE,
         url="https://batdongsan.com.vn/cho-thue-can-ho-chung-cu-duong-28-phuong-phuoc-long-khu-do-thi-vcn-phuoc-long-2/cho-xh1-nha-trang-7-trieu-thang-pr46183238"),
]

FACEBOOK = [
    dict(price="6,0 млн ₫/мес", area="2 спальни, 1 с/у", district="Nguyễn Thiện Thuật (центр)",
         title="Căn hộ 2 phòng ngủ trung tâm Nha Trang",
         address="Chung cư số 7 Nguyễn Thiện Thuật, tầng 6, Nha Trang",
         phone="см. по ссылке (кнопка «Message» в посте) — автор Dương Yến",
         desc="Пост от 26 июня, «золотая» локация в самом центре города. На фото — гостиная с ТВ, спальня с двуспальной кроватью, обеденный стол со стульями.",
         amenity_note="Кухонный уголок и кровати видны на фото поста; кондиционер/холодильник/стиралка отдельно текстом не указаны — смотрите фото по ссылке.",
         url="https://www.facebook.com/groups/593714207638751/posts/3039362199740594",
         note="Прямая ссылка на пост, проверена 15.08.2026."),
    dict(price="8,5 млн ₫/мес", area="2 спальни", district="Bắc Nha Trang (север)",
         title="Chung cư Hoàng Quân đầy đủ nội thất",
         address="ЖК Hoàng Quân, Bắc Nha Trang", phone="см. по ссылке — автор Nguyễn Nga",
         desc="Пост от 29 июня, «trống sẵn» = свободна для заезда сейчас. Полностью меблирована — на фото диван, обеденная группа, двуспальные кровати с шкафами.",
         amenity_note="Мебель полная по фото (гостиная, спальни); кондиционер/холодильник/стиралка отдельно текстом не указаны.",
         url="https://www.facebook.com/groups/593714207638751/posts/3042751936068287",
         note="Прямая ссылка на пост, проверена 15.08.2026. Заменяет более раннюю неактуальную запись — тот исходный пост (пустая квартира за 6,0 млн) на 15.08.2026 в группе не находится; эта карточка — актуальное действующее объявление по той же ЖК."),
    dict(price="6,5 млн ₫/мес", area="1 спальня", district="Phước Long",
         title="Căn hộ 1PN khu vực Phước Long",
         address="Phước Long, Nha Trang", phone="+84 819 070 270 (WhatsApp, Zalo) — автор Hồng Liên",
         desc="На фото — кухня со встроенным гарнитуром и техникой, спальня с кондиционером на стене, отдельный санузел.",
         amenity_note="✓ Кондиционер и кухня видны на фото. Холодильник/стиралка/рабочее место — не видно явно, уточняйте.",
         url="https://www.facebook.com/groups/593714207638751/posts/3029787557364725",
         note="Прямая ссылка на пост, проверена 15.08.2026."),
    dict(price="6,0 млн ₫/мес", area="1 спальня", district="Бак Нячанг (север)",
         title="Căn hộ 1 phòng ngủ — Lê Văn Huân",
         address="Lê Văn Huân, Phía Bắc Nha Trang", phone="см. по ссылке — автор Nguyễn Thị Mỹ Hiệp",
         desc="Север города, 1 спальня.",
         amenity_note=GENERIC_AMENITY_NOTE,
         url="https://www.facebook.com/groups/593714207638751/posts/3086083898401757",
         note="Прямая ссылка на пост, проверена 15.08.2026."),
    dict(price="6,5 млн ₫/мес", area="—", district="Vĩnh Điềm Trung",
         title="Chung cư CT5 Vĩnh Điềm Trung",
         address="CT5, Khu đô thị Vĩnh Điềm Trung, Nha Trang", phone="см. по ссылке — автор Kim Qui",
         desc="Свободна с 22 июня. На фото — гостиная с диваном и обеденной зоной (стеклянный стол, красные стулья), полностью меблирована.",
         amenity_note="Мебель полная по фото (гостиная, кухонный уголок); техника (кондиционер/холодильник/стиралка) отдельно не подписана.",
         url="https://www.facebook.com/groups/593714207638751/posts/3032292100447604",
         note="Прямая ссылка на пост, проверена 15.08.2026."),
    dict(price="6,8 млн ₫/мес", area="студия", district="Khu Phố Tây (центр)",
         title="Căn hộ studio Khu Phố Tây",
         address="Khu Phố Tây, Nha Trang", phone="см. по ссылке — автор Mỹ Duyên",
         desc="Студия в «западном квартале» (туристический центр). На фото — отдельная кухня со встроенной плитой, вытяжкой и мойкой, спальная зона с кроватями.",
         amenity_note="✓ Кухня со встроенной техникой (плита, вытяжка) видна на фото. Кондиционер/холодильник/стиралка/рабочее место — не подписаны отдельно.",
         url="https://www.facebook.com/groups/593714207638751/posts/3088753294801484",
         note="Прямая ссылка на пост, проверена 15.08.2026. Заменяет более раннюю неактуальную запись без точного адреса."),
]

print("6-9 млн: Chợ Tốt", len(CHOTOT), "| Batdongsan", len(BATDONGSAN), "| Facebook", len(FACEBOOK))
