# -*- coding: utf-8 -*-
"""Telegram, вторая часть разбора 10 сентября 2026: 4 строки Нячанга.

ПЕРВЫЕ СТРОКИ В УКРУПНЁННОМ БАК НЯЧАНГЕ, и вот почему это не догадка. Три поста
называют местность Vinh Hoa -- ward, которого нет среди двенадцати привычных
районов сайта. Куда он попал после реформы 2025 года, сказал не я: Nominatim
возвращает для тамошних школ адрес «Trường Tiểu học Vĩnh Hòa, Ngô Văn Sở,
Phường Bắc Nha Trang» -- то есть OSM уже перевесил адреса на новые районы. То же
подтверждает и точка в границах из nt_overpass.json, по которым рисуется карта.
Это ровно тот же род доказательства, что и поле ward_name_v3 у Chợ Tốt: сказал
источник, а не сессия.

  Проверка заодно вскрыла ловушку геокодера: на запрос «Vĩnh Nguyên» Nominatim
  молча отдаёт рынок Винь Хай на другом конце города. Совпадение по имени там,
  где имени нет, -- это не ответ, и полагаться можно только на тот случай, когда
  в адресе стоит само искомое название.

STAR CITY взят потому, что пост сам называет район («Star City, район Lộc Thọ»).
Сборщик не смог назначить ему цену: рядом с арендой в 12 000 000 ₫ стоит строка
«смена постельного белья 1 000 000 ₫/месяц», и два числа сделали цену
неоднозначной. Аренда названа дважды и совпадает -- 12 млн.

ЧЕГО НЕ ВЗЯЛИ ИЗ ТОГО ЖЕ ОСТАТКА:
  * студия 35 м² в Vega City попадалась дважды -- у nyachang_arenda и у
    Viet_life; та же площадь, та же цена, те же коммунальные до рубля. Это одна
    квартира у двух агентств, заведена один раз;
  * пять постов arenda_nhatrang по Океанусу -- «2 спальни, 2 санузла» без
    площади и этажа, по 12,5-18,5 млн. От уже стоящих строк того же ЖК их
    отличает только цена, а она у перевыложенных объявлений и так гуляет;
  * Marina Suites, Maple, Virgo, Panorama, Gold Coast -- комплексов нет на сайте
    ни в одной строке, привязать не к чему;
  * шесть объявлений dalatapartment: им от 15 до 107 дней, чистка по возрасту
    снесла бы их в ту же ночь.
"""
from listing_lock import insert_listings

IDS = [2000586, 2000587, 2000588, 2000589]

NEW_SRC = r'''
L(2000586,"nha-trang","btr","Квартира",15000000,40,
  "1-спальная квартира 40 м² в Винь Хоа, север Нячанга — новая, сдаётся впервые: окна на восток, кондиционер, лифт, полная меблировка. Минута пешком до моря. Депозит месяц, оплата помесячно, договор от трёх месяцев; электричество 4 500 ₫ за кВт·ч, вода 100 000 ₫ с человека, обслуживание с Wi-Fi и вывозом мусора 120 000 ₫ в месяц.",
  "https://t.me/nyachang_arenda/639413","сегодня",0,source="telegram",
  descEn="A 40 m² one-bedroom flat in Vĩnh Hòa, northern Nha Trang — brand new and let for the first time: east-facing windows, air conditioning, a lift and full furnishing. A minute's walk from the sea. One month deposit, paid monthly, contract from three months; electricity 4,500 ₫ per kWh, water 100,000 ₫ per person, service including WiFi and rubbish collection 120,000 ₫ a month.",
  details={"photos": ["https://cdn5.telesco.pe/file/Biq_jMgWLfIRy84dd9hSoqtfviCoKdkl7UQ1fpbzxmj2WXIVNumGy-H2VBZ-zaiYNn92ZnUJZpNMX0PCuAehrKDYvhxB2xgdHCvfopy8Yhnz6TBDLpyuQY0RQZ3-9_GbzKppZT-SXhNpRZh79XenTdhRbS_4-OWqS_dDrRTyz1s-EgOEz9gRqKGOh-NeA7TcjKJXVfRNdRq-IcXMhSDz-IoAvzqcb897gABsUfc-5QxCpYl9rZ37tjUr00b8XvVzhReGpw4c2gpZweaLiQYImW9160DPFlBocrF9CaggqtZ1ua6vH_rRvx8t_DrHf5WN3-M064nMsbleG5flAwZ7NA.jpg", "https://cdn5.telesco.pe/file/EiORM-JSKTkOKWkBQxjAWtgk_-FHWOBT4nvTpKh7pyYLAcUkxeIMvpyxuNgCjPloAHRJvxOYZDEa-phKIf2l9wYu7mL_-Oi7-g9NwMDFybw7415HUmZ47vpBliPLuPma3JGS4n03PdgL-cNvayO1RdghvsWoRz65g0YxXBVX5k8x4zyKADsC90TihjXrZ5f0ZeG3YPqzq3XDBI4SfqDD00eVyq5h-hKp6ILQgTg0uK0oNz-YjteEFUvrpUKE9bAzl_HPcDmODAW0BpUTB10wEMDwzWFI8H7Hss47uE_PPRwePe3steBtiD-NLP-nH0VPtmJi9PKrEbH81xxE4sdWVA.jpg", "https://cdn5.telesco.pe/file/LzVMcBoTmGywM31zDOAmcCWdt8itlPf7Q-ch_vC8ltCgeHVTvAI5HgAPj2nnJb-Qjy2syuCLB8llYSnpL81sOlVMElmrof272oyJoGsdFaTR9UvepkPRXopMoixIitl9J27Tn5t5ciqse7SW-Pq1sphCXmoX4yokm9chGhX0cxCe6nJCeKWPouClkrcA_ftGmVfJQMhyf26QqxXep2-XgOeN3EdcDOrhM9WBbW_h0YYnuc-YFB8EU-LTm6uQPrRKrDTwgFsb6sQFYkBLcXiFiSQdv5Ago4KNFzVde95x90jGMYefJNkoaZhHSbKNCvR-VwFRW2dj8_5YXY8N-b0PYw.jpg", "https://cdn5.telesco.pe/file/LXmlFlCI7eY9BGVNEU2tGOnJJln7mMjL5dQLkja2TIfPYDK6nOTw57wVXanmHITk5RcE3gOS79sPxsJ8R_C167GSw28vsWAxUetUQ-_mSZwd1hTim-_lxyu_b7Dybu5B8yW-mJwhV6AYoAcOePxzZs7L58v4XJ4jQ1c4oikgEOCm5Lw7k5flTxP7adqbDVdV4Y0M94Gsz2huFxqFWC79cniHPQzNyyGWyO5keKDE_oqhsgJVa81Bh3SrjAr3AHM-4ES_oEK2F1LGTrwp4jz2WpR3ytqSykj3eGbuZLbVzE8G9Tit_DGmhTg2TG2cWwuD-bA3jz29vh0EuZ3ElpHfwA.jpg", "https://cdn5.telesco.pe/file/I22V2K4yrobYRxnyOIZ7WBrj0inXRX24xem_C9rGZMpawOUk4202lw9ufP2fVAgsmChAmT4F9uGIInNBFpmJ41U4hUXZU2jRnY8LK_pYUVenU02A2rEDxmDA-FfmayF5xdMH78-k9cUEQAIqUngOLj4u3EQ2VzMoER83oxbcffnHRolF7jGW4muKvABRa9HhB9bQme1DSPsuQnhXqXIF5JJ0qnyHh52scqnf8T5uXGKE8RlBDTKciNqmkFy6Lic55tS4bt6CRPhc0DDHsafHlPJMXWeX0_SvhJysRDyehMiq1Ol09hGK-2t5eSCiGr0voJVsQBsOI2ALMTWbtGQ3qw.jpg", "https://cdn5.telesco.pe/file/Xiw8qsnar17wshxBryGnv1kjA5bt0-63ohvSFWe3FcF1q9dtSVd1ltDYHUXY2naVDY-cxzxcj6hR0MoZrh5bMAdp5ek8ChkYOtOWL6rv2RbL3s6pbHSIgJWsfk5mf-sHhvEc0NDAfhIocUO7ZjIbGiLLPky8-SmSnN9VgdwojnchDcmc6nGwgXs03BqX52huZcfB9XDgshW0jqLO8d6pZu83j7IzRZwTicmMVDo1NBIFAoo5ylyJBKofnC-vIvlEyiEji-ExTnP5dI8eCXOCpgdkoh1T_hEviJ1JgQhFhMpQ-Hv85eTsTQQ0f0CpycRiqei_7Fd7cw2OWLSayNjkKA.jpg"], "notice": "Источник — пост в телеграм-канале. Ссылка ведёт на сам пост, а не на канал, поэтому дата размещения здесь настоящая, взята из поста. Фотографии тоже из поста и лежат на серверах Telegram. Цену и условия подтверждайте у автора объявления.", "noticeEn": "Source: a post in a Telegram channel. The link points at the post itself rather than the channel, so the date shown is the real posting date taken from it. The photos come from the same post and are hosted by Telegram. Confirm the price and terms with the poster."}),
L(2000587,"nha-trang","btr","Квартира",16000000,40,
  "1-спальная квартира 40 м² в Винь Хоа, север Нячанга — окна на восток, лифт, полная меблировка, тихий район. Минута пешком до моря. Депозит месяц, оплата помесячно, договор от трёх месяцев; электричество 4 500 ₫ за кВт·ч, вода 100 000 ₫ с человека, обслуживание с Wi-Fi и вывозом мусора 120 000 ₫ в месяц.",
  "https://t.me/nyachang_arenda/639405","сегодня",0,source="telegram",
  descEn="A 40 m² one-bedroom flat in Vĩnh Hòa, northern Nha Trang — east-facing windows, a lift, full furnishing and a quiet neighbourhood. A minute's walk from the sea. One month deposit, paid monthly, contract from three months; electricity 4,500 ₫ per kWh, water 100,000 ₫ per person, service including WiFi and rubbish collection 120,000 ₫ a month.",
  details={"photos": ["https://cdn5.telesco.pe/file/N1x7HjxKwVmC_1EzJgPda3_dHzjmHf7ZYV37FBFEY9dzmZNoGxYpwn-4jO3KhI0a_KCrYrT0SaHg3IxdaCOyaGG4xUyH1aAbSRyBJN2CGMu3YIbh3gGzkc9SaFiPjSVaYVLzTRla02BUH1CPD1bTXcZ6RlD9vKpYkpb0p4_fJ3aQCg6tA4t8hpiryZq_OfdwnDpZxKlDc16JfVjbMlmVgpJYkpDw97cuU9kJtmSkQ9SS9thaJTshnOrJ2YeDuFQsx-yoB2TNgwN7OOLuT3EpO1LbhYZxaKW_fdWqprSNb-Ifcm5y9jp16-oX8SWL88OVDsp1LGIW5tupsTxR9weqDw.jpg", "https://cdn5.telesco.pe/file/CBrK3IiprlpeRnb5c-rWTRaGFpItE07nc4ksHj5hfYbAvzDiTn1QacbhVxS7xdacdEbL78bGRD8rV65PFnApQQOFuq-9KSysAvNlPDHrSeDLE-o5QHpm9wU_bxrsPururxKcfQ-CD9xLfbmXdQrpRf8WDC7tQajDl3Nt_mDVV7UAfHAtAq6-5v25t9BkbQB8WP7vUQ_wmspw3B-s_MFTlH4m0Zt0QlIFtBt1QemrRf_tozCfFuR77-g_Fne2--vQ6zKT2_LnQS_u-A_1kO1d_7_E9l9A6rCxuUySdE1WtnV7MgO9XMTryQN1fh8mVEj6TOowE_GEsUCiZB_6YQgipw.jpg", "https://cdn5.telesco.pe/file/uYLoN8vFTgGpJ8D0iVkgtDR8CX20pw_FrGZT40SecBOAr0LEb1T_y0esBINYKMVuO-uACfVSv4hvM_JS9ccDcz-v9L-psNsqSIUzQ-NJKiVfVqB7yoZk3eF_B6XzvtJDGO85pinuMryqiQZIS6MoTzovODTxcBrlnkiCnW3xji2kkO4MgX01me_3GTuO1KJHWEvdX-0f_zPItdZIOsTpS_CHOMD7xyzrB2lzqrdDrXnDwLhwufHCvS9DKBkGKPqhBWWcnyk6rvTJz7kvKeVWTIg0YhfFnjtoCYIU15Xn3OhsuDS7OqDf3Xmv3GuYAB4lY75JWOu3f7vqqUG4SQrTbw.jpg", "https://cdn5.telesco.pe/file/dK7LUHeoDi-mTI1AsM99m-zBW20GtAjxXuuOfBaJhiGC-iab1jOJ-bwKiFtN-NXtGl68IDvUKLgcHfla-qkU-a-Gt9jLPOt3wdZOa7rteyAHSJSRxWayVjI7uYTX6GU20j-ywrzyuUVlp-qLrrNUIxjtqCc8LP8hY-6qssPhF9bEjiNE4WR0CY-8388lNxO_YHIiY0sYhjhaSCLNz5_XX33gaF2ihq_9c6eL5wW3pNwdUFQ_ftVFqr-AnV7lCsWCRkK2uFEnmBRlOGWh8GNqPpyRpLMTZ9ljssKF0qqcoA2dMGeNFH3VDsMT-pj5mXY6r_6mljKKPP2gGn3kstaBdQ.jpg", "https://cdn5.telesco.pe/file/S4KGeNROnQUypwDD27OB3yhUwS29sley_ZP6FSewb4KEaGroU4W5ICS751sG_SgTpLINQYQCwaZamoITv8FekrzVMexd2GugHoIVeY0IJTxlrWwTUh2FByecWyWRC21hdYFfBvTMELcLHPe5RQrutlZ3i8D8CC8VIHvm_da8qICTbJmPA_BzjIDR047dzDT8vOAlsVx3edrHOnbMAArM2cqJBda6AGyt91MEqR8BUFHgCTbfcrSYDlYBG9Y-6mPGZ-zuT2WJIO2kDUTgByQIzUiRzajcLmJu3RjytzzS-r1_bA2x7KIxLAhq2lcHi-zYzhWudyfAphOxX-MAybnvdg.jpg", "https://cdn5.telesco.pe/file/ESc7hG06_u5QSWNU-3FkeiTVQ_SSMNLqW2nQYrB1ijX1unmYo2Ph9JYwiEF8St5cGwq6JsePy4zrAvAfwM79rmNfkEDO02Q-7po7KodEUmQKIPD0LS9zFoSAMi--bO8kXtNN21ed-ezTH8SJmHg8geipRpqCoVDLnGZ7hdWjRCstOiDPctYa0RiS6zWOo1zwZcSiuXbNViqQm6T6wyPH-MS4j79W7E3lUNHV4kVXxjn_QGW5vC0Y4evvMJkXQiSKkq96se474soITINTQw1rgR9xphAV8ycU346hsQ2p5TvyKTKEOLoXVVppLjry0wMA2ryhR6eteHDjiIMXOytUjg.jpg"], "notice": "Источник — пост в телеграм-канале. Ссылка ведёт на сам пост, а не на канал, поэтому дата размещения здесь настоящая, взята из поста. Фотографии тоже из поста и лежат на серверах Telegram. Цену и условия подтверждайте у автора объявления.", "noticeEn": "Source: a post in a Telegram channel. The link points at the post itself rather than the channel, so the date shown is the real posting date taken from it. The photos come from the same post and are hosted by Telegram. Confirm the price and terms with the poster."}),
L(2000588,"nha-trang","btr","Студия",14000000,35,
  "Студия 35 м² в комплексе Vega City, Винь Хоа, север Нячанга — окна на восток, лифт, полная меблировка, хозяева в доме не живут. Минута пешком до моря. Депозит месяц, оплата помесячно, договор от трёх месяцев; электричество 4 500 ₫ за кВт·ч, вода 100 000 ₫ с человека, обслуживание с Wi-Fi и вывозом мусора 120 000 ₫ в месяц.",
  "https://t.me/nyachang_arenda/639422","сегодня",0,source="telegram",
  descEn="A 35 m² studio in the Vega City complex, Vĩnh Hòa, northern Nha Trang — east-facing windows, a lift, full furnishing, and no landlords living in the building. A minute's walk from the sea. One month deposit, paid monthly, contract from three months; electricity 4,500 ₫ per kWh, water 100,000 ₫ per person, service including WiFi and rubbish collection 120,000 ₫ a month.",
  details={"photos": ["https://cdn5.telesco.pe/file/E5UrVvpbwYLyDRqaVZxikIzj6xeO6cOyXYprn7mkNny_fOlQ48EuA-vn03zdPoo0PXu0vOJe821b2TpDMt6QqehBgJ3MevxhnhXZDPm8ICgH0JHmgWlMtw1tstR2A0MLMI234PDF1V1EEbDlgswobpRBZM4F_onYL23TRXT0eFbozIVJroAUKujBqM97nBStknb-e2AEXvHaY5ADQUvzZGGiPe_mK7g422kgoWB5gA3XFCJ0DdRga7Gm-b7_WWDgKYwJOCNJcJpCV9IZfF-cbddEhuJIzHpoPD_50PYxDQn1ymAYX82rk5V0wInNxbxpaeG7pZUu7lFYyMOBx79_Nw.jpg", "https://cdn5.telesco.pe/file/AAIPkJ4_1AHl14D6Rt5As38149C6J3P79sqbiM6-v-2Wb15vx93siLuUxuvdNcm0GqGbeAcbsyIw3R_aPA-9PijNPUxj28xiYjHSO9qTvxYFHc09o9GlCjIQewfbQOoMY_jwFnYMsxLqSuw1SXLtVfMNg6_tGck7hTKWfubK8iDQEzbgzwiWSUzV19wsTvfMa0sWLXbbqjJ2gzXe2uXbAouq0v1W6W26nKk7HhxLe5-Fm3PfUCmcXoYceOhOSycXZtp0YyJnmyIvm4I7NDKvjHIjGHq8WWXOnV8L96F6RadQfV5mjBeEHTg91NGnJNTXXeA_MRzcDG5LXIFGTwg28w.jpg", "https://cdn5.telesco.pe/file/CbGtaETz4ZU3bo4PMXv2vg_c01Yxsasv-WgabzTSpUq8kqqJJtNmDb6K-9wFz0QpiufAp-Y_suQymk7I9O0wFbWPNNRmKJPbzSor8gQiL_6LT89uWMzqRKOlectXZhvuHNbgZvAiGyDbxtb_WvxsiPelzuDenjAUKu6kCz9ssXqHoREvAlhQdM7NXzfDEEEUK7fYNERMA3KGySh6uKp7_7_oAjKJAtUwMqnNndFdPpFTKvCyGYrpu5YQJwgASJAYJN2BNYl0F4pJvjt87T0FrDHgfyLfgkNGr58qFF4AJtP-jP5G-T61bkExgelVwx6elmkhd3RpGxRiCcU41qJgjQ.jpg", "https://cdn5.telesco.pe/file/bUKTfrcg0vox62aRKNvYmd7VF28jaZmbTfuEhDp_7OdOVG90N-8xazjLJBE30i4bAuhWC_SEsjd1x-vXRoCr6FJRDQ4Tnro3Uzqjqa9qtROvyIBw-eWemgBQOO4eY5DbQycBuwErIKXyVDL9h9z4rG1PYz8CcWZ-b2dJD2Tr2UPa6vI4bSTCYq13hz9XfmDfTtVdHP8Pp_kXJ4I0GSiy_mb7CF-iynvnGo0Geidnp6ozKpQeaLGCSUJ4cKgjJiN1FZ8QeVjTQ_TmH50Z2wg7SmmPMRE0TCcSlEDEVlX9z8n7N9cn-l94cLfo163_lpVoxEg2ThLnq5yXypesTe1gMw.jpg", "https://cdn5.telesco.pe/file/dCYz3iiB92MOIGH8Rx4PmVN9w9jUWntemvbl6Ob3Tw8ElTHlN0dCxT8ZAm2iS86MiWDh56cqkYHiBEAL6gxNNqdy3N5MctDVrUh5Qjhq06HagopNRX-00YP6ej-ygy5VOa5ZaDaC8QEL7U5mpKdI-Oa3eM8JTPgj7Ua6Mmgd8KBLAGjpMNtOqFmJl82OveCsm3gv8aQyan1dpUCW7Gwr_7SyX8X-xE3Qpch_ce_U1bM-aS09R14PrYpccf7bfZxJEfC0XTxWDHxtuYOEiWDH_pJIHZgQvWsKzaTE381jjlcBHmIS9nzD8rg3kUgHbDuquzVaa-KrDJRmgieql-2a6A.jpg", "https://cdn5.telesco.pe/file/kdQHrJ6IN-Sa4Dc5PY-zuGAsRcHWzx7h8-iuX-jrkbma9RNZgB8M-OobUtKx6hdonTwgoHxUwlezZVsoyk9FuGJ3OnvM_TPjioiyTerOBT-mjAdd-VL86dB7nQwJbrYbSzCK5l2y2WfubXqxF4h-4Qbqz1meRHln5aSHL19nDyqdE4VmESRK_VEhAi6o39LCrh1bZBOsnTu58sJta02Up2bOwVuvokYCcS_oJlZhLkAsuF50RGlrg1a2dHRu8H3sghXGKFcxwyBIw6moKYRZ9t_9BY5cg1EilAtNp78rofVA7oTwJj1yhSndvCiASJiD-QeWsmQImv-IlAmHkZTFIw.jpg"], "notice": "Источник — пост в телеграм-канале. Ссылка ведёт на сам пост, а не на канал, поэтому дата размещения здесь настоящая, взята из поста. Фотографии тоже из поста и лежат на серверах Telegram. Цену и условия подтверждайте у автора объявления.", "noticeEn": "Source: a post in a Telegram channel. The link points at the post itself rather than the channel, so the date shown is the real posting date taken from it. The photos come from the same post and are hosted by Telegram. Confirm the price and terms with the poster."}),
L(2000589,"nha-trang","lt","Квартира",12000000,35,
  "Квартира 35 м² в комплексе Star City на набережной Чан Фу, Лок Тхо — высокий этаж, вид на море, две кухонные зоны, премиальная меблировка. Бассейн и спортзал в комплексе, пляж напротив. Депозит месяц, оплата помесячно, договор от трёх месяцев; электричество 3 770 ₫ за кВт·ч, обслуживание 700 000 ₫, Wi-Fi 230 000 ₫, бассейн со спортзалом 700 000 ₫ в месяц.",
  "https://t.me/Viet_life_niachang/177928","сегодня",0,source="telegram",
  descEn="A 35 m² flat in the Star City complex on the Trần Phú seafront, Lộc Thọ — a high floor, a sea view, two kitchen areas and premium furnishing. A pool and a gym in the complex, the beach across the road. One month deposit, paid monthly, contract from three months; electricity 3,770 ₫ per kWh, building service 700,000 ₫, WiFi 230,000 ₫, pool and gym 700,000 ₫ a month.",
  details={"photos": ["https://cdn4.telesco.pe/file/b04zlXeka5IKA97EkuhlsFnkNggonGAspVGug_fs-B5K9J68CztXam5797Zpj_pVG3M2R48LYmj70IU2OsJEyZBKXKtbPIadyOwCra4Cp-_89bb2GVRZvN3PTa0FzrrWWkq2513SnQVZRtBDY7BsSL_9M-hAhnWYl0tD01lqUqJ54fXnYNJ74qClS_otbWAR9MEERlpxIYnr9SxkXXAbX4q4CY5ksCDD0bWsn8SUSOCU_Ikz2MPTlVY3El0zG6mtEVLy0misTcgB0xJj3eVdFQcpMxUilDO96cF0mSOYok_KRJv1hM8Z9CrXESCIJfAHrHrdOaIQ7gxtXsSXWc1OLA.jpg", "https://cdn4.telesco.pe/file/P619kGc21FF4RScLtQ65-npyRgwbZzHrHm7p9A3dhG0OxX0dVwxDoV8Ztslc_dxE9XIScjxenuwUroOlbIGZe6ci0rfQ9ilhj6t_d3Eg0Slt9CZeqrmUcPxWhYY6V5dkWaWvVVFT8cgZep0NAg0G_IhYgXeTeF1z9UQ4m2yVCXMj6tBz_aUO8gxiTXWYIcdPBcwl-PWxvT0qZJFBULKDYFGTu9GfsO2OzTTVErW3ls_Fug4ayMukbmn3UGUImGMZp3s-t3UGZugF0c0d_W-0jvO-UlADPgymwd0a0ViyIqpkFnql16ybrgpFe4Iu0JTzBKAQGr0MPr1dtpQBrwDj5g.jpg", "https://cdn4.telesco.pe/file/XJFru-4LHTxe81Pjd9mrbf0Bek6Jlzf2xchQaBzRHEpE1RaGUK3FEcVv-tpUAIVoJhOzr5NqT8dq0q19tmL5yT-j3onoGW3y3Yaakz_xAmvTCTXr0VWu3YISEHG6e1ksJK7VSMnrUjKE85LrXRmWcpMO0itgvDvbEI02DkRwafn6bAaYEQopjVK2734-XkDfVg7MXCHPmBnrwrxl7wcaEI1P8oyz2Me8AO9qqJwHo6wGYxamVMf8Lt2g8PwiAgT3PX-W5bJgbpMn3RMCDexo8qbMxraFDgnXiMoaUYi0Kkya4JmIJZNAeGMXKOLqVSbp6m1g9tPogKicBXrAtcBJ0w.jpg", "https://cdn4.telesco.pe/file/RbY3mzo90cHypcMR1gyXun3mgwITVGAX79zjY0zOcXIei11T_HZdA4G19378R2wMzcmIxujK8ngce7eKCFkmRGJY1oCSUy-7PMWx3mUmYqIih6e9MwG_k2_h_d6EpuCEzkDoyIvEUtetTV92HiIUuSuri7nPGjEgVEmfdsj5hhh6YdziP0SF5IDJe-KI3EedaEgJPoXZ491fCKk-StRMwmCsSyO7EjMonrJG9ybluH7Ulh-m0gL40hMxRwvWNm307sPHB-8SJoXFDu3xON2k_1h40VL0NzQG2kqiCD57Nu45uhaA1r6zmFKnx_8PZik6PtO8yQtPVxsN--kwXXySsA.jpg", "https://cdn4.telesco.pe/file/BRYaCZdTTsJHcLZR28DfgoUAkcJfJ2sO9mfmhnIk6RceEWnLjXH16rUQT_MuoxcJffQSrBX_xGs8MM1EOUNWX-YZgqsdoU_xdsdCd88ub9FLMqaQKCVEaqQUCs5cuhk2NPdzgfU-3pQb9UBjiBNHmz0WLlq-5_73Cm_IvmTzE8oBVfmKE-PzQbtOuss4pegnJfAkNoXaXMDut9j9XoRq1hqNhzubPr8j_15liO-BCrVjcktQLT4S9ZZlAo5RiVxuobxfsBbum_eyx-d-G7VUebv-dBsA_YUO5n0QitGsrvYKB4oGupOtEP24XN58HWZf6nSuBGkaPmNQT6JJYfjIJA.jpg", "https://cdn4.telesco.pe/file/tnBxpMctE4e00HPSG--FH1RyqHDgtwA4BAzhHBs896nN68Rix_6oGW3f9BI6h3BO5OyQ9SKeUelStuG-Q9amFbWOp3xIabNdqjUEXWPCaK1wy7ASxhvObYkI-qyBXrYuJhAKai3tgUcYwXwhaXfQyJY-hf39EJP-t2V8gzbgbsQ4DjxBX6Vqtut_zxQOaw4C0_le-WdzisU0_yoM7_acFF8LhJMcMheR5EYfuNqVRBTxdvpHgRgMHD4CatnsTBWBZaH0GETeVH0lN5DGsgV1KAy8v__6t8G9SledTolUA2PR8XGpZi_sXYIl2Iw8FdDcbKh9ebrduQgxlKCx--3Eew.jpg"], "notice": "Источник — пост в телеграм-канале. Ссылка ведёт на сам пост, а не на канал, поэтому дата размещения здесь настоящая, взята из поста. Фотографии тоже из поста и лежат на серверах Telegram. Цену и условия подтверждайте у автора объявления.", "noticeEn": "Source: a post in a Telegram channel. The link points at the post itself rather than the channel, so the date shown is the real posting date taken from it. The photos come from the same post and are hosted by Telegram. Confirm the price and terms with the poster."}),
'''

if __name__ == "__main__":
    insert_listings(NEW_SRC, IDS, owner=__file__)
