# -*- coding: utf-8 -*-
"""dotproperty.com.ph, автоматический сбор: 3 объявлений, 2026-09-16.

Партию собрал collect_dotproperty.py -- без модели в контуре. Район взят из
разметки объявления (точное совпадение с CITIES либо однозначный прецедент на
сайте), описание собрано из полей разметки, возраст выведен из UUIDv7 в
идентификаторе записи и не превышает 7 дней.

Объявления, локальность которых не совпала ни с одним нашим районом и не имеет
однозначного прецедента, пропущены, а не приписаны к соседнему.
"""
from listing_lock import insert_listings

IDS = [3000837, 3000838, 3000839]

N_RU = "Описание собрано программой из разметки объявления на dotproperty.com.ph — тип, спальни, санузлы, площадь, локальность и цена. Рекламный текст объявления не пересказан. Район поставлен по локальности из той же разметки; она изредка расходится с адресом в тексте объявления, поэтому адрес стоит сверить по ссылке. Дату размещения портал не публикует: возраст выведен из идентификатора записи (UUIDv7 хранит время создания) и означает «не моложе»."
N_EN = "This description was assembled by a program from the ad's own schema.org markup on dotproperty.com.ph — type, bedrooms, bathrooms, size, locality and price. The ad's marketing text is not retold. The district comes from the locality in that same markup, which occasionally disagrees with the address written in the ad, so check the address at the source. The portal publishes no posting date: the age is derived from the record id (a UUIDv7 carries its creation time) and means 'no newer than'."

NEW_SRC = r'''
L(3000837,"cebu","cap","Квартира",38000,40,
  "1-спальная квартира, 40 м², Luz, Себу — 1 санузел.",
  "https://www.dotproperty.com.ph/ads/1-bedroom-condo-for-rent-in-luz-cebu_21058c004176-a50f-f042-6ab5-0e1f9f89","сегодня",0,source="dotproperty",cur="PHP",
  descEn="1-bedroom flat, 40 m², Luz, Cebu City — 1 bathroom.",
  details={"photos": ["https://pix.dotproperty.co.th/eyJidWNrZXQiOiJwcmQtbGlmdWxsY29ubmVjdC1iYWNrZW5kLWIyYi1pbWFnZXMiLCJrZXkiOiJwcm9wZXJ0aWVzLzAxYTBhOGI5LTRlZjMtNzU5YS1hOTRmLTMyODU5OWQxNDk4Ny8wMWEwYThiOS1kMTg3LTczZjktYTBkNi0wMTI5M2IxYTIyZDEuanBnIiwiYnJhbmQiOiJkb3Rwcm9wZXJ0eSIsImVkaXRzIjp7InJvdGF0ZSI6bnVsbCwicmVzaXplIjp7IndpZHRoIjo0OTAsImhlaWdodCI6MzI1LCJmaXQiOiJjb3ZlciJ9fX0=", "https://pix.dotproperty.co.th/eyJidWNrZXQiOiJwcmQtbGlmdWxsY29ubmVjdC1iYWNrZW5kLWIyYi1pbWFnZXMiLCJrZXkiOiJwcm9wZXJ0aWVzLzAxYTBhOGI5LTRlZjMtNzU5YS1hOTRmLTMyODU5OWQxNDk4Ny8wMWEwYThiOS1kMTg3LTczZjktYTBkNi0wMTI5M2IxYTIyZDEuanBnIiwiYnJhbmQiOiJkb3Rwcm9wZXJ0eSIsImVkaXRzIjp7InJvdGF0ZSI6bnVsbCwicmVzaXplIjp7IndpZHRoIjo5NiwiaGVpZ2h0Ijo2NCwiZml0IjoiY292ZXIifX19", "https://pix.dotproperty.co.th/eyJidWNrZXQiOiJwcmQtbGlmdWxsY29ubmVjdC1iYWNrZW5kLWIyYi1pbWFnZXMiLCJrZXkiOiJwcm9wZXJ0aWVzLzAxYTBhOGI5LTRlZjMtNzU5YS1hOTRmLTMyODU5OWQxNDk4Ny8wMWEwYThiOS1kMTg3LTczZjktYTBkNi0wMTI5M2IxYTIyZDEuanBnIiwiYnJhbmQiOiJkb3Rwcm9wZXJ0eSIsImVkaXRzIjp7InJvdGF0ZSI6bnVsbCwicmVzaXplIjp7IndpZHRoIjoxMTcwLCJoZWlnaHQiOjc4MCwiZml0IjoiY292ZXIifX19", "https://pix.dotproperty.co.th/eyJidWNrZXQiOiJwcmQtbGlmdWxsY29ubmVjdC1iYWNrZW5kLWIyYi1pbWFnZXMiLCJrZXkiOiJwcm9wZXJ0aWVzLzAxYTBhOGI5LTRlZjMtNzU5YS1hOTRmLTMyODU5OWQxNDk4Ny8wMWEwYThiOS1kMTg3LTczZjktYTBkNi0wMTI5M2IxYTIyZDEuanBnIiwiYnJhbmQiOiJkb3Rwcm9wZXJ0eSIsImVkaXRzIjp7InJvdGF0ZSI6bnVsbCwicmVzaXplIjp7IndpZHRoIjoyNzUsImhlaWdodCI6MTU1LCJmaXQiOiJjb3ZlciJ9fX0=", "https://pix.dotproperty.co.th/eyJidWNrZXQiOiJwcmQtbGlmdWxsY29ubmVjdC1iYWNrZW5kLWIyYi1pbWFnZXMiLCJrZXkiOiJwcm9wZXJ0aWVzLzAxYTBhOGI5LTRlZjMtNzU5YS1hOTRmLTMyODU5OWQxNDk4Ny8wMWEwYThiOS1kMjJmLTcwZWQtYTE5ZC0yYjE1ZDVhZGZmNmIuanBnIiwiYnJhbmQiOiJkb3Rwcm9wZXJ0eSIsImVkaXRzIjp7InJvdGF0ZSI6bnVsbCwicmVzaXplIjp7IndpZHRoIjo5NiwiaGVpZ2h0Ijo2NCwiZml0IjoiY292ZXIifX19", "https://pix.dotproperty.co.th/eyJidWNrZXQiOiJwcmQtbGlmdWxsY29ubmVjdC1iYWNrZW5kLWIyYi1pbWFnZXMiLCJrZXkiOiJwcm9wZXJ0aWVzLzAxYTBhOGI5LTRlZjMtNzU5YS1hOTRmLTMyODU5OWQxNDk4Ny8wMWEwYThiOS1kMjJmLTcwZWQtYTE5ZC0yYjE1ZDVhZGZmNmIuanBnIiwiYnJhbmQiOiJkb3Rwcm9wZXJ0eSIsImVkaXRzIjp7InJvdGF0ZSI6bnVsbCwicmVzaXplIjp7IndpZHRoIjoxMTcwLCJoZWlnaHQiOjc4MCwiZml0IjoiY292ZXIifX19"], "notice": "RU_N", "noticeEn": "EN_N"}),
L(3000838,"cebu","cap","Квартира",60000,90,
  "2-спальная квартира, 90 м², Luz, Себу — 1 санузел.",
  "https://www.dotproperty.com.ph/ads/2-bedroom-condo-for-rent-in-luz-cebu_cfb93441fc14-1bf0-e872-37eb-8c1f9f89","сегодня",0,source="dotproperty",cur="PHP",
  descEn="2-bedroom flat, 90 m², Luz, Cebu City — 1 bathroom.",
  details={"photos": ["https://pix.dotproperty.co.th/eyJidWNrZXQiOiJwcmQtbGlmdWxsY29ubmVjdC1iYWNrZW5kLWIyYi1pbWFnZXMiLCJrZXkiOiJwcm9wZXJ0aWVzLzAxYTBhOGQxLWViMjYtNzIxYi05YWU4LTU4ZGE4NTU2MGVhZC8wMWEwYThkMi1mY2M5LTcyZjUtYjE0OS1kNjNkOTUyNDM1NWIuanBnIiwiYnJhbmQiOiJkb3Rwcm9wZXJ0eSIsImVkaXRzIjp7InJvdGF0ZSI6bnVsbCwicmVzaXplIjp7IndpZHRoIjo5NiwiaGVpZ2h0Ijo2NCwiZml0IjoiY292ZXIifX19", "https://pix.dotproperty.co.th/eyJidWNrZXQiOiJwcmQtbGlmdWxsY29ubmVjdC1iYWNrZW5kLWIyYi1pbWFnZXMiLCJrZXkiOiJwcm9wZXJ0aWVzLzAxYTBhOGQxLWViMjYtNzIxYi05YWU4LTU4ZGE4NTU2MGVhZC8wMWEwYThkMi1mY2M5LTcyZjUtYjE0OS1kNjNkOTUyNDM1NWIuanBnIiwiYnJhbmQiOiJkb3Rwcm9wZXJ0eSIsImVkaXRzIjp7InJvdGF0ZSI6bnVsbCwicmVzaXplIjp7IndpZHRoIjoxMTcwLCJoZWlnaHQiOjc4MCwiZml0IjoiY292ZXIifX19", "https://pix.dotproperty.co.th/eyJidWNrZXQiOiJwcmQtbGlmdWxsY29ubmVjdC1iYWNrZW5kLWIyYi1pbWFnZXMiLCJrZXkiOiJwcm9wZXJ0aWVzLzAxYTBhOGQxLWViMjYtNzIxYi05YWU4LTU4ZGE4NTU2MGVhZC8wMWEwYThkMi1mYWE0LTcwNzctYTBkNy1kMjNhOTI0ZDJhOGEuanBnIiwiYnJhbmQiOiJkb3Rwcm9wZXJ0eSIsImVkaXRzIjp7InJvdGF0ZSI6bnVsbCwicmVzaXplIjp7IndpZHRoIjo0OTAsImhlaWdodCI6MzI1LCJmaXQiOiJjb3ZlciJ9fX0=", "https://pix.dotproperty.co.th/eyJidWNrZXQiOiJwcmQtbGlmdWxsY29ubmVjdC1iYWNrZW5kLWIyYi1pbWFnZXMiLCJrZXkiOiJwcm9wZXJ0aWVzLzAxYTBhOGQxLWViMjYtNzIxYi05YWU4LTU4ZGE4NTU2MGVhZC8wMWEwYThkMi1mYWE0LTcwNzctYTBkNy1kMjNhOTI0ZDJhOGEuanBnIiwiYnJhbmQiOiJkb3Rwcm9wZXJ0eSIsImVkaXRzIjp7InJvdGF0ZSI6bnVsbCwicmVzaXplIjp7IndpZHRoIjo5NiwiaGVpZ2h0Ijo2NCwiZml0IjoiY292ZXIifX19", "https://pix.dotproperty.co.th/eyJidWNrZXQiOiJwcmQtbGlmdWxsY29ubmVjdC1iYWNrZW5kLWIyYi1pbWFnZXMiLCJrZXkiOiJwcm9wZXJ0aWVzLzAxYTBhOGQxLWViMjYtNzIxYi05YWU4LTU4ZGE4NTU2MGVhZC8wMWEwYThkMi1mYWE0LTcwNzctYTBkNy1kMjNhOTI0ZDJhOGEuanBnIiwiYnJhbmQiOiJkb3Rwcm9wZXJ0eSIsImVkaXRzIjp7InJvdGF0ZSI6bnVsbCwicmVzaXplIjp7IndpZHRoIjoxMTcwLCJoZWlnaHQiOjc4MCwiZml0IjoiY292ZXIifX19", "https://pix.dotproperty.co.th/eyJidWNrZXQiOiJwcmQtbGlmdWxsY29ubmVjdC1iYWNrZW5kLWIyYi1pbWFnZXMiLCJrZXkiOiJwcm9wZXJ0aWVzLzAxYTBhOGQxLWViMjYtNzIxYi05YWU4LTU4ZGE4NTU2MGVhZC8wMWEwYThkMi1mYWE0LTcwNzctYTBkNy1kMjNhOTI0ZDJhOGEuanBnIiwiYnJhbmQiOiJkb3Rwcm9wZXJ0eSIsImVkaXRzIjp7InJvdGF0ZSI6bnVsbCwicmVzaXplIjp7IndpZHRoIjoyNzUsImhlaWdodCI6MTU1LCJmaXQiOiJjb3ZlciJ9fX0="], "notice": "RU_N", "noticeEn": "EN_N"}),
L(3000839,"cebu","bnl","Дом",110000,462,
  "5-спальный дом, 462 м², Banilad, Себу — 4 санузла.",
  "https://www.dotproperty.com.ph/ads/5-bedroom-house-for-rent-in-banilad-cebu_48965137d88f-8ae0-5922-0c23-ed1f9f89","сегодня",0,source="dotproperty",cur="PHP",
  descEn="5-bedroom house, 462 m², Banilad, Cebu City — 4 bathrooms.",
  details={"photos": ["https://pix.dotproperty.co.th/eyJidWNrZXQiOiJwcmQtbGlmdWxsY29ubmVjdC1iYWNrZW5kLWIyYi1pbWFnZXMiLCJrZXkiOiJwcm9wZXJ0aWVzLzAxYTBhOGNiLTY3ZDktNzcwNC05YmYxLWExMWMyNjg0MzAxNS8wMWEwYThjYy1lNTRkLTcwM2UtOWU4ZS05OGIyMmMxYjY4ZjQuanBnIiwiYnJhbmQiOiJkb3Rwcm9wZXJ0eSIsImVkaXRzIjp7InJvdGF0ZSI6bnVsbCwicmVzaXplIjp7IndpZHRoIjo0OTAsImhlaWdodCI6MzI1LCJmaXQiOiJjb3ZlciJ9fX0=", "https://pix.dotproperty.co.th/eyJidWNrZXQiOiJwcmQtbGlmdWxsY29ubmVjdC1iYWNrZW5kLWIyYi1pbWFnZXMiLCJrZXkiOiJwcm9wZXJ0aWVzLzAxYTBhOGNiLTY3ZDktNzcwNC05YmYxLWExMWMyNjg0MzAxNS8wMWEwYThjYy1lNTRkLTcwM2UtOWU4ZS05OGIyMmMxYjY4ZjQuanBnIiwiYnJhbmQiOiJkb3Rwcm9wZXJ0eSIsImVkaXRzIjp7InJvdGF0ZSI6bnVsbCwicmVzaXplIjp7IndpZHRoIjo5NiwiaGVpZ2h0Ijo2NCwiZml0IjoiY292ZXIifX19", "https://pix.dotproperty.co.th/eyJidWNrZXQiOiJwcmQtbGlmdWxsY29ubmVjdC1iYWNrZW5kLWIyYi1pbWFnZXMiLCJrZXkiOiJwcm9wZXJ0aWVzLzAxYTBhOGNiLTY3ZDktNzcwNC05YmYxLWExMWMyNjg0MzAxNS8wMWEwYThjYy1lNTRkLTcwM2UtOWU4ZS05OGIyMmMxYjY4ZjQuanBnIiwiYnJhbmQiOiJkb3Rwcm9wZXJ0eSIsImVkaXRzIjp7InJvdGF0ZSI6bnVsbCwicmVzaXplIjp7IndpZHRoIjoxMTcwLCJoZWlnaHQiOjc4MCwiZml0IjoiY292ZXIifX19", "https://pix.dotproperty.co.th/eyJidWNrZXQiOiJwcmQtbGlmdWxsY29ubmVjdC1iYWNrZW5kLWIyYi1pbWFnZXMiLCJrZXkiOiJwcm9wZXJ0aWVzLzAxYTBhOGNiLTY3ZDktNzcwNC05YmYxLWExMWMyNjg0MzAxNS8wMWEwYThjYy1lNTRkLTcwM2UtOWU4ZS05OGIyMmMxYjY4ZjQuanBnIiwiYnJhbmQiOiJkb3Rwcm9wZXJ0eSIsImVkaXRzIjp7InJvdGF0ZSI6bnVsbCwicmVzaXplIjp7IndpZHRoIjoyNzUsImhlaWdodCI6MTU1LCJmaXQiOiJjb3ZlciJ9fX0=", "https://pix.dotproperty.co.th/eyJidWNrZXQiOiJwcmQtbGlmdWxsY29ubmVjdC1iYWNrZW5kLWIyYi1pbWFnZXMiLCJrZXkiOiJwcm9wZXJ0aWVzLzAxYTBhOGNiLTY3ZDktNzcwNC05YmYxLWExMWMyNjg0MzAxNS8wMWEwYThjZC0wM2QwLTcyZTEtOTBiOS0xN2VlZDZjODViNmEuanBnIiwiYnJhbmQiOiJkb3Rwcm9wZXJ0eSIsImVkaXRzIjp7InJvdGF0ZSI6bnVsbCwicmVzaXplIjp7IndpZHRoIjo5NiwiaGVpZ2h0Ijo2NCwiZml0IjoiY292ZXIifX19", "https://pix.dotproperty.co.th/eyJidWNrZXQiOiJwcmQtbGlmdWxsY29ubmVjdC1iYWNrZW5kLWIyYi1pbWFnZXMiLCJrZXkiOiJwcm9wZXJ0aWVzLzAxYTBhOGNiLTY3ZDktNzcwNC05YmYxLWExMWMyNjg0MzAxNS8wMWEwYThjZC0wM2QwLTcyZTEtOTBiOS0xN2VlZDZjODViNmEuanBnIiwiYnJhbmQiOiJkb3Rwcm9wZXJ0eSIsImVkaXRzIjp7InJvdGF0ZSI6bnVsbCwicmVzaXplIjp7IndpZHRoIjoxMTcwLCJoZWlnaHQiOjc4MCwiZml0IjoiY292ZXIifX19"], "notice": "RU_N", "noticeEn": "EN_N"}),
'''

NEW_SRC = NEW_SRC.replace("RU_N", N_RU).replace("EN_N", N_EN)

if __name__ == "__main__":
    insert_listings(NEW_SRC, IDS, owner=__file__)
