# -*- coding: utf-8 -*-
"""Группы Facebook, ночной сбор ПК 11 сентября 2026: 21 строк из 39 кандидатов.

Первый ночной сбор, который программа сделала сама. Вход в профиль сборщика
восстановлен, лента групп заменена поиском по группе (fb_collect.py 1.2), фото
берутся из вложений самого поста. У каждой строки первое фото сверено с текстом
поста глазами -- расхождений нет.

РАЙОН -- ПО СЛОВАМ ПОСТА, ПО ЕДИНОГЛАСНОМУ ПРЕЦЕДЕНТУ ИЛИ НИКАК:
  * Думагете: Dauin и Valencia названы в постах (Lipayo -- «Lipayo Dauin»);
    Casa Alicia -- единственная строка сайта, в Candau-Ay;
  * Себу: Lahug, Talisay, Apas, Labangon названы; Pit-os и Metropolis --
    все строки сайта в Talamban;
  * Манила: Xavierville 2 -- «QC»; The Camden Place -- прецеденты «camden»,
    «vito cruz», «la salle», «ocampo» все в Малате;
  * Хошимин: пять квартир в Тхао Дьен -- ключ ak (Phường An Khánh); улицы
    Quốc Hương, Nguyễn Văn Hưởng и Xa Lộ Hà Nội стоят на сайте только в ak;
  * Нячанг: Nguyễn Thiện Thuật -- семь строк в Tân Lập против одной в новом
    центральном районе (который Tân Lập и включает); Napoleon Castle --
    единственная строка, в Vĩnh Phước;
  * Дананг: Sơn Trà и Liên Chiểu названы в постах.

ЦЕНА ВЗЯТА ИЗ ТЕКСТА, А НЕ У СБОРЩИКА, у пяти строк:
  * у двух нячангских сборщик принял за цену кусок телефона «0386 715 274»
    (715 274 ₫ вместо 13 и 12,5 млн) -- ошибка разбора, чинится отдельно;
  * у Valencia -- цена с мебелью (25 000 ₱), без мебели 18 000 ₱ в описании;
  * у двух даннангских в посте «от 10 млн» и «11 млн» -- взято названное.

ОТСЕЯНО (18):
  * нет района на сайте и нет прецедента: Cantil-e (дважды), Kalunasan,
    San Juan, Sampaloc, Paco, Bình Thạnh Ward 22, Tân Định;
  * пост называет два района сразу: «Tisa–Labangon»;
  * слова поста спорят с прецедентом -- тогда не выбираем: Katipunan (пост --
    Tisa, строка сайта -- Labangon), Hùng Vương (пост -- Lộc Thọ, строка --
    Phước Hòa), Phạm Văn (пост -- Sơn Trà, три строки -- An Hải), Củ Chi у
    Хон Чонга (подсказка района -- Vĩnh Hải, строки сайта -- Vĩnh Phước);
  * прецедент расколот: Panorama, The Ponte;
  * не аренда: Golf Hill Gardens -- продажа в рассрочку («rent to own»,
    взнос 244 тыс ₱, цена 4,1 млн ₱); подселение на P. Paterno -- поиск соседки;
  * без единой фотографии: комната в Daro.
"""
from listing_lock import insert_listings

IDS = [3000523, 3000524, 3000525, 3000526, 3000527, 3000528, 3000529, 3000530, 3000531, 3000532, 3000533, 3000534, 3000535, 3000536, 3000537, 3000538, 3000539, 3000540, 3000541, 3000542, 3000543]

NEW_SRC = r'''
L(3000523,"dumaguete","cdy","Дом",50000,None,
  "Дом с полной меблировкой в Casa Alicia, Думагете — открытая гостиная со столовой, кондиционеры во всём доме, современная кухня с барной стойкой. На втором этаже 3 спальни со встроенными шкафами, в главной — свой санузел и гардеробная; ещё один санузел внизу. Видеонаблюдение снаружи. Свободен с 30 сентября; до центра и университета Силлиман 10 минут.",
  "https://www.facebook.com/groups/153191128587086/posts/2231309210775257/","сегодня",0,source="fbgroup",cur="PHP",
  descEn="A fully furnished house in Casa Alicia, Dumaguete — an open-plan living and dining area, air conditioning throughout and a modern kitchen with a breakfast bar. Upstairs are 3 bedrooms with built-in wardrobes, the master with its own bathroom and a walk-in closet; one more bathroom downstairs. Exterior CCTV. Available from 30 September; 10 minutes to downtown and Silliman University.",
  details={"photos": ["assets/fb_photos/2231309210775257/01.webp", "assets/fb_photos/2231309210775257/02.webp", "assets/fb_photos/2231309210775257/03.webp", "assets/fb_photos/2231309210775257/04.webp", "assets/fb_photos/2231309210775257/05.webp"], "notice": "Источник — пост в группе Facebook. Точной даты размещения группа не отдаёт: в данных страницы её нет, а видимые метки времени принадлежат комментариям. Указанный возраст — это время с проверки: 11 сентября 2026 объявление было открыто по ссылке и подтверждено живым. Фотографии взяты из самого поста и хранятся на этом сайте: ссылки Facebook на изображения подписаны и живут около четырёх дней. Цена в филиппинских песо, как в посте.", "noticeEn": "Source: a post in a Facebook group. The group gives no exact posting date — it is absent from the page data, and the visible timestamps belong to comments. The age shown is time since verification: on 11 September 2026 the listing was opened by its link and confirmed live. The photos come from the post itself and are stored on this site, because Facebook's image links are signed and expire in about four days. The price is in Philippine pesos, as in the post."}),
L(3000524,"dumaguete","dau","Дом",125000,None,
  "Дом на первой линии в Дауине, в охраняемом посёлке с видеонаблюдением — полная меблировка, 5 спален (у главной свой санузел с ванной и гардеробная), 4 санузла. Своя скважина, центральный бак горячей воды, генератор, бесплатный Starlink. Садовник три раза в неделю и помощница по дому два раза в неделю включены.",
  "https://www.facebook.com/groups/153191128587086/posts/2225051174734394/","сегодня",0,source="fbgroup",cur="PHP",
  descEn="A beachfront house in Dauin, inside a guarded compound with CCTV — fully furnished, 5 bedrooms (the master with its own bathroom with a tub and a walk-in closet), 4 bathrooms. Its own deep well, a central hot-water tank, a generator and free Starlink WiFi. A gardener three times a week and a helper twice a week are included.",
  details={"photos": ["assets/fb_photos/2225051174734394/01.webp", "assets/fb_photos/2225051174734394/02.webp", "assets/fb_photos/2225051174734394/03.webp", "assets/fb_photos/2225051174734394/04.webp", "assets/fb_photos/2225051174734394/05.webp"], "notice": "Источник — пост в группе Facebook. Точной даты размещения группа не отдаёт: в данных страницы её нет, а видимые метки времени принадлежат комментариям. Указанный возраст — это время с проверки: 11 сентября 2026 объявление было открыто по ссылке и подтверждено живым. Фотографии взяты из самого поста и хранятся на этом сайте: ссылки Facebook на изображения подписаны и живут около четырёх дней. Цена в филиппинских песо, как в посте.", "noticeEn": "Source: a post in a Facebook group. The group gives no exact posting date — it is absent from the page data, and the visible timestamps belong to comments. The age shown is time since verification: on 11 September 2026 the listing was opened by its link and confirmed live. The photos come from the post itself and are stored on this site, because Facebook's image links are signed and expire in about four days. The price is in Philippine pesos, as in the post."}),
L(3000525,"dumaguete","val","Квартира",25000,None,
  "Новая квартира в Валенсии в двух уровнях — 3 спальни (одна на первом этаже), 2 санузла, полная меблировка; огороженная территория с воротами, большая парковка, тихое место рядом со школой. Вода бесплатно. Без мебели — 18 000 ₱. Депозит за месяц и месяц вперёд; до Думагете 15 минут.",
  "https://www.facebook.com/groups/153191128587086/posts/2228726647700180/","сегодня",0,source="fbgroup",cur="PHP",
  descEn="A brand-new two-level apartment in Valencia — 3 bedrooms (one on the ground floor), 2 bathrooms and full furnishing; fenced and gated, with a large car park, in a quiet spot near a school. Water is free. Unfurnished it is 18,000 ₱. One month deposit and one month in advance; 15 minutes to Dumaguete.",
  details={"photos": ["assets/fb_photos/2228726647700180/01.webp", "assets/fb_photos/2228726647700180/02.webp", "assets/fb_photos/2228726647700180/03.webp", "assets/fb_photos/2228726647700180/04.webp", "assets/fb_photos/2228726647700180/05.webp"], "notice": "Источник — пост в группе Facebook. Точной даты размещения группа не отдаёт: в данных страницы её нет, а видимые метки времени принадлежат комментариям. Указанный возраст — это время с проверки: 11 сентября 2026 объявление было открыто по ссылке и подтверждено живым. Фотографии взяты из самого поста и хранятся на этом сайте: ссылки Facebook на изображения подписаны и живут около четырёх дней. Цена в филиппинских песо, как в посте.", "noticeEn": "Source: a post in a Facebook group. The group gives no exact posting date — it is absent from the page data, and the visible timestamps belong to comments. The age shown is time since verification: on 11 September 2026 the listing was opened by its link and confirmed live. The photos come from the post itself and are stored on this site, because Facebook's image links are signed and expire in about four days. The price is in Philippine pesos, as in the post."}),
L(3000526,"dumaguete","dau","Квартира",12000,None,
  "Квартира в Липайо, Дауин — 2 спальни с кондиционером, санузел, частичная меблировка: холодильник, газовая плита, диван, кровать с матрасом. Накопительный бак для воды, огороженная территория.",
  "https://www.facebook.com/groups/153191128587086/posts/2223649681541210/","сегодня",0,source="fbgroup",cur="PHP",
  descEn="An apartment in Lipayo, Dauin — 2 air-conditioned bedrooms, a bathroom and partial furnishing: a fridge, a gas stove, a sofa and a bed with a mattress. A water tank and a fenced yard.",
  details={"photos": ["assets/fb_photos/2223649681541210/01.webp", "assets/fb_photos/2223649681541210/02.webp", "assets/fb_photos/2223649681541210/03.webp", "assets/fb_photos/2223649681541210/04.webp", "assets/fb_photos/2223649681541210/05.webp"], "notice": "Источник — пост в группе Facebook. Точной даты размещения группа не отдаёт: в данных страницы её нет, а видимые метки времени принадлежат комментариям. Указанный возраст — это время с проверки: 11 сентября 2026 объявление было открыто по ссылке и подтверждено живым. Фотографии взяты из самого поста и хранятся на этом сайте: ссылки Facebook на изображения подписаны и живут около четырёх дней. Цена в филиппинских песо, как в посте.", "noticeEn": "Source: a post in a Facebook group. The group gives no exact posting date — it is absent from the page data, and the visible timestamps belong to comments. The age shown is time since verification: on 11 September 2026 the listing was opened by its link and confirmed live. The photos come from the post itself and are stored on this site, because Facebook's image links are signed and expire in about four days. The price is in Philippine pesos, as in the post."}),
L(3000527,"cebu","lah","Студия",15000,None,
  "Студия в Mivesa Garden Residences на ул. Салинас, Лахуг — полная меблировка и техника, Wi-Fi. Цена с платой за обслуживание дома; месяц вперёд и депозит за два месяца. Рядом IT Park, рестораны и торговые центры.",
  "https://www.facebook.com/groups/563896434149922/posts/2372909199915294/","сегодня",0,source="fbgroup",cur="PHP",
  descEn="A studio in Mivesa Garden Residences on Salinas St, Lahug — fully furnished, with appliances and WiFi. The rent includes the condo dues; one month in advance and two months deposit. IT Park, restaurants and malls are nearby.",
  details={"photos": ["assets/fb_photos/2372909199915294/01.webp", "assets/fb_photos/2372909199915294/02.webp", "assets/fb_photos/2372909199915294/03.webp", "assets/fb_photos/2372909199915294/04.webp", "assets/fb_photos/2372909199915294/05.webp"], "notice": "Источник — пост в группе Facebook. Точной даты размещения группа не отдаёт: в данных страницы её нет, а видимые метки времени принадлежат комментариям. Указанный возраст — это время с проверки: 11 сентября 2026 объявление было открыто по ссылке и подтверждено живым. Фотографии взяты из самого поста и хранятся на этом сайте: ссылки Facebook на изображения подписаны и живут около четырёх дней. Цена в филиппинских песо, как в посте.", "noticeEn": "Source: a post in a Facebook group. The group gives no exact posting date — it is absent from the page data, and the visible timestamps belong to comments. The age shown is time since verification: on 11 September 2026 the listing was opened by its link and confirmed live. The photos come from the post itself and are stored on this site, because Facebook's image links are signed and expire in about four days. The price is in Philippine pesos, as in the post."}),
L(3000528,"cebu","tls","Квартира",15000,None,
  "Новая 1-спальная квартира на Mansueto Road, Табунок, Талисай — первые жильцы, парковка для машины, до шоссе минута-две. Рядом Gaisano Tabunok и Robinsons Southtown. Вода включена в цену; месяц вперёд и депозит за два месяца.",
  "https://www.facebook.com/groups/563896434149922/posts/2369556196917261/","сегодня",0,source="fbgroup",cur="PHP",
  descEn="A new one-bedroom flat on Mansueto Road, Tabunok, Talisay — first tenants, car parking, a minute or two from the highway. Gaisano Tabunok and Robinsons Southtown are nearby. Water is included; one month in advance and two months deposit.",
  details={"photos": ["assets/fb_photos/2369556196917261/01.webp", "assets/fb_photos/2369556196917261/02.webp", "assets/fb_photos/2369556196917261/03.webp", "assets/fb_photos/2369556196917261/04.webp", "assets/fb_photos/2369556196917261/05.webp"], "notice": "Источник — пост в группе Facebook. Точной даты размещения группа не отдаёт: в данных страницы её нет, а видимые метки времени принадлежат комментариям. Указанный возраст — это время с проверки: 11 сентября 2026 объявление было открыто по ссылке и подтверждено живым. Фотографии взяты из самого поста и хранятся на этом сайте: ссылки Facebook на изображения подписаны и живут около четырёх дней. Цена в филиппинских песо, как в посте.", "noticeEn": "Source: a post in a Facebook group. The group gives no exact posting date — it is absent from the page data, and the visible timestamps belong to comments. The age shown is time since verification: on 11 September 2026 the listing was opened by its link and confirmed live. The photos come from the post itself and are stored on this site, because Facebook's image links are signed and expire in about four days. The price is in Philippine pesos, as in the post."}),
L(3000529,"cebu","itp","Комната",4000,None,
  "Новая комната у Ejocs 2, Апас — свой санузел, можно готовить и стирать, огороженная территория с видеонаблюдением, электричество по отдельному счётчику, вода с человека. Только для женщин, на одного-двух; без детей, животных и гостей. Вторая комната — 4 500 ₱. Месяц депозита и месяц вперёд; рядом IT Park и CMall.",
  "https://www.facebook.com/groups/563896434149922/posts/2370296823509865/","сегодня",0,source="fbgroup",cur="PHP",
  descEn="A newly built room near Ejocs 2, Apas — its own bathroom, cooking and laundry allowed, a gated yard with CCTV, electricity on a sub-meter and water per head. Women only, for one or two; no children, pets or visitors. The second room is 4,500 ₱. One month deposit and one month in advance; IT Park and CMall are nearby.",
  details={"photos": ["assets/fb_photos/2370296823509865/01.webp", "assets/fb_photos/2370296823509865/02.webp", "assets/fb_photos/2370296823509865/03.webp", "assets/fb_photos/2370296823509865/04.webp", "assets/fb_photos/2370296823509865/05.webp"], "notice": "Источник — пост в группе Facebook. Точной даты размещения группа не отдаёт: в данных страницы её нет, а видимые метки времени принадлежат комментариям. Указанный возраст — это время с проверки: 11 сентября 2026 объявление было открыто по ссылке и подтверждено живым. Фотографии взяты из самого поста и хранятся на этом сайте: ссылки Facebook на изображения подписаны и живут около четырёх дней. Цена в филиппинских песо, как в посте.", "noticeEn": "Source: a post in a Facebook group. The group gives no exact posting date — it is absent from the page data, and the visible timestamps belong to comments. The age shown is time since verification: on 11 September 2026 the listing was opened by its link and confirmed live. The photos come from the post itself and are stored on this site, because Facebook's image links are signed and expire in about four days. The price is in Philippine pesos, as in the post."}),
L(3000530,"cebu","tlm","Дом",35000,160,
  "Двухэтажный дом 160 м² с мебелью в посёлке Metropolis у CIS, Пит-ос — 3 спальни, 3 санузла, комната для прислуги, гараж на две машины; участок 127 м². Депозит за два месяца и два месяца вперёд, осмотр по договорённости.",
  "https://www.facebook.com/groups/1735327053393688/posts/4528691044057261/","сегодня",0,source="fbgroup",cur="PHP",
  descEn="A furnished two-storey 160 m² house in the Metropolis subdivision near CIS, Pit-os — 3 bedrooms, 3 bathrooms, a maid's room and a two-car garage; a 127 m² lot. Two months deposit and two months in advance, viewing by appointment.",
  details={"photos": ["assets/fb_photos/4528691044057261/01.webp", "assets/fb_photos/4528691044057261/02.webp", "assets/fb_photos/4528691044057261/03.webp", "assets/fb_photos/4528691044057261/04.webp", "assets/fb_photos/4528691044057261/05.webp"], "notice": "Источник — пост в группе Facebook. Точной даты размещения группа не отдаёт: в данных страницы её нет, а видимые метки времени принадлежат комментариям. Указанный возраст — это время с проверки: 11 сентября 2026 объявление было открыто по ссылке и подтверждено живым. Фотографии взяты из самого поста и хранятся на этом сайте: ссылки Facebook на изображения подписаны и живут около четырёх дней. Цена в филиппинских песо, как в посте.", "noticeEn": "Source: a post in a Facebook group. The group gives no exact posting date — it is absent from the page data, and the visible timestamps belong to comments. The age shown is time since verification: on 11 September 2026 the listing was opened by its link and confirmed live. The photos come from the post itself and are stored on this site, because Facebook's image links are signed and expire in about four days. The price is in Philippine pesos, as in the post."}),
L(3000531,"cebu","lab","Комната",2500,None,
  "Койко-место в комнате на шестерых, Salvador Extension, Лабангон — полная меблировка, кондиционер, двухъярусная кровать с матрасом и подушкой, личный шкафчик, стол со стулом; после ремонта. Два общих санузла с душем. Электричество, вода и интернет отдельно; готовить и стирать нельзя (рисоварку можно). Свободно с 1 октября.",
  "https://www.facebook.com/groups/1735327053393688/posts/1808557076990144/","сегодня",0,source="fbgroup",cur="PHP",
  descEn="A bed space in a room for six on Salvador Extension, Labangon — fully furnished, air-conditioned, a bunk bed with a mattress and pillow, a personal locker and a desk with a chair; newly renovated. Two shared bathrooms with showers. Electricity, water and internet are extra; no cooking or laundry (a rice cooker is allowed). Available from 1 October.",
  details={"photos": ["assets/fb_photos/1808557076990144/01.webp", "assets/fb_photos/1808557076990144/02.webp", "assets/fb_photos/1808557076990144/03.webp", "assets/fb_photos/1808557076990144/04.webp"], "notice": "Источник — пост в группе Facebook. Точной даты размещения группа не отдаёт: в данных страницы её нет, а видимые метки времени принадлежат комментариям. Указанный возраст — это время с проверки: 11 сентября 2026 объявление было открыто по ссылке и подтверждено живым. Фотографии взяты из самого поста и хранятся на этом сайте: ссылки Facebook на изображения подписаны и живут около четырёх дней. Цена в филиппинских песо, как в посте.", "noticeEn": "Source: a post in a Facebook group. The group gives no exact posting date — it is absent from the page data, and the visible timestamps belong to comments. The age shown is time since verification: on 11 September 2026 the listing was opened by its link and confirmed live. The photos come from the post itself and are stored on this site, because Facebook's image links are signed and expire in about four days. The price is in Philippine pesos, as in the post."}),
L(3000532,"manila","qzc","Дом",60000,250,
  "Двухэтажный таунхаус в Xavierville 2, Кесон-Сити — после ремонта; участок 120 м², около 250 м² площади. Внизу гостиная, столовая, кухня с кладовой, комната прислуги со своим санузлом, гостевой туалет и гараж на машину; наверху главная спальня с санузлом и гардеробом, ещё две спальни с общим санузлом и веранда, на третьем этаже открытая терраса. Рядом Ateneo, UP и Miriam. Договор минимум на два года, оплата чеками на будущие даты.",
  "https://www.facebook.com/groups/224805677963542/posts/2575869156190504/","сегодня",0,source="fbgroup",cur="PHP",
  descEn="A two-storey townhouse in Xavierville 2, Quezon City — newly renovated; a 120 m² lot and about 250 m² of floor space. Downstairs: a living and dining area, a kitchen with a pantry, a maid's room with its own bathroom, a powder room and a one-car garage; upstairs: a master bedroom with a bathroom and closet, two more bedrooms with a shared bathroom and a veranda, and an open-air third floor. Ateneo, UP and Miriam are close. Minimum two-year contract, paid by post-dated cheques.",
  details={"photos": ["assets/fb_photos/2575869156190504/01.webp", "assets/fb_photos/2575869156190504/02.webp", "assets/fb_photos/2575869156190504/03.webp", "assets/fb_photos/2575869156190504/04.webp", "assets/fb_photos/2575869156190504/05.webp"], "notice": "Источник — пост в группе Facebook. Точной даты размещения группа не отдаёт: в данных страницы её нет, а видимые метки времени принадлежат комментариям. Указанный возраст — это время с проверки: 11 сентября 2026 объявление было открыто по ссылке и подтверждено живым. Фотографии взяты из самого поста и хранятся на этом сайте: ссылки Facebook на изображения подписаны и живут около четырёх дней. Цена в филиппинских песо, как в посте.", "noticeEn": "Source: a post in a Facebook group. The group gives no exact posting date — it is absent from the page data, and the visible timestamps belong to comments. The age shown is time since verification: on 11 September 2026 the listing was opened by its link and confirmed live. The photos come from the post itself and are stored on this site, because Facebook's image links are signed and expire in about four days. The price is in Philippine pesos, as in the post."}),
L(3000533,"manila","mla","Квартира",25000,None,
  "1-спальная квартира с полной меблировкой в The Camden Place, угол Taft Avenue и P. Ocampo — пешком до станции LRT Vito Cruz, рядом De La Salle, St. Benilde, St. Scholastica's и торговый центр R Square. Месяц вперёд, депозит за два месяца, оплата чеками; без посредников.",
  "https://www.facebook.com/groups/224805677963542/posts/2579759342468152/","сегодня",0,source="fbgroup",cur="PHP",
  descEn="A fully furnished one-bedroom flat in The Camden Place, at the corner of Taft Avenue and P. Ocampo — walking distance to LRT Vito Cruz station, near De La Salle, St. Benilde, St. Scholastica's and the R Square mall. One month in advance, two months deposit, post-dated cheques; no agents.",
  details={"photos": ["assets/fb_photos/2579759342468152/01.webp", "assets/fb_photos/2579759342468152/02.webp", "assets/fb_photos/2579759342468152/03.webp", "assets/fb_photos/2579759342468152/04.webp", "assets/fb_photos/2579759342468152/05.webp"], "notice": "Источник — пост в группе Facebook. Точной даты размещения группа не отдаёт: в данных страницы её нет, а видимые метки времени принадлежат комментариям. Указанный возраст — это время с проверки: 11 сентября 2026 объявление было открыто по ссылке и подтверждено живым. Фотографии взяты из самого поста и хранятся на этом сайте: ссылки Facebook на изображения подписаны и живут около четырёх дней. Цена в филиппинских песо, как в посте.", "noticeEn": "Source: a post in a Facebook group. The group gives no exact posting date — it is absent from the page data, and the visible timestamps belong to comments. The age shown is time since verification: on 11 September 2026 the listing was opened by its link and confirmed live. The photos come from the post itself and are stored on this site, because Facebook's image links are signed and expire in about four days. The price is in Philippine pesos, as in the post."}),
L(3000534,"ho-chi-minh","ak","Студия",15500000,35,
  "Студия 35 м² у ул. Куок Хыонг, Тхао Дьен — современная мебель, большой шкаф, стиральная машина, большое окно. Интернет, парковка байка и уборка два раза в неделю включены. Свободна сейчас.",
  "https://www.facebook.com/groups/chungcumini.canhodichvu.phongtrotphcm/posts/1840738980578158/","сегодня",0,source="fbgroup",
  descEn="A 35 m² studio near Quốc Hương street, Thảo Điền — modern furniture, a large wardrobe, a washing machine and a big window. Internet, motorbike parking and cleaning twice a week are included. Available now.",
  details={"photos": ["assets/fb_photos/1840738980578158/01.webp", "assets/fb_photos/1840738980578158/02.webp", "assets/fb_photos/1840738980578158/03.webp", "assets/fb_photos/1840738980578158/04.webp", "assets/fb_photos/1840738980578158/05.webp"], "notice": "Источник — пост в группе Facebook. Точной даты размещения группа не отдаёт: в данных страницы её нет, а видимые метки времени принадлежат комментариям. Указанный возраст — это время с проверки: 11 сентября 2026 объявление было открыто по ссылке и подтверждено живым. Фотографии взяты из самого поста и хранятся на этом сайте: ссылки Facebook на изображения подписаны и живут около четырёх дней.", "noticeEn": "Source: a post in a Facebook group. The group gives no exact posting date — it is absent from the page data, and the visible timestamps belong to comments. The age shown is time since verification: on 11 September 2026 the listing was opened by its link and confirmed live. The photos come from the post itself and are stored on this site, because Facebook's image links are signed and expire in about four days."}),
L(3000535,"ho-chi-minh","ak","Квартира",14000000,40,
  "1-спальная квартира 40 м² у улицы 64, Тхао Дьен — один санузел. Обслуживание дома, уборка раз в неделю, интернет и парковка байка включены; можно с кошкой. Свободна сейчас.",
  "https://www.facebook.com/groups/chungcumini.canhodichvu.phongtrotphcm/posts/1802133711105352/","сегодня",0,source="fbgroup",
  descEn="A 40 m² one-bedroom flat near Street 64, Thảo Điền — one bathroom. Building service, a weekly clean, internet and motorbike parking are included; cats are welcome. Available now.",
  details={"photos": ["assets/fb_photos/1802133711105352/01.webp", "assets/fb_photos/1802133711105352/02.webp", "assets/fb_photos/1802133711105352/03.webp", "assets/fb_photos/1802133711105352/04.webp", "assets/fb_photos/1802133711105352/05.webp"], "notice": "Источник — пост в группе Facebook. Точной даты размещения группа не отдаёт: в данных страницы её нет, а видимые метки времени принадлежат комментариям. Указанный возраст — это время с проверки: 11 сентября 2026 объявление было открыто по ссылке и подтверждено живым. Фотографии взяты из самого поста и хранятся на этом сайте: ссылки Facebook на изображения подписаны и живут около четырёх дней.", "noticeEn": "Source: a post in a Facebook group. The group gives no exact posting date — it is absent from the page data, and the visible timestamps belong to comments. The age shown is time since verification: on 11 September 2026 the listing was opened by its link and confirmed live. The photos come from the post itself and are stored on this site, because Facebook's image links are signed and expire in about four days."}),
L(3000536,"ho-chi-minh","ak","Квартира",18000000,40,
  "1-спальная квартира 40 м² на Ханойском шоссе (Xa Lộ Hà Nội), Тхао Дьен — полная меблировка. Обслуживание дома, Wi-Fi, парковка байка и уборка включены; без животных. Депозит месяц, свободна сейчас.",
  "https://www.facebook.com/groups/chungcumini.canhodichvu.phongtrotphcm/posts/1802247057760684/","сегодня",0,source="fbgroup",
  descEn="A fully furnished 40 m² one-bedroom flat on Xa Lộ Hà Nội, Thảo Điền. Building service, WiFi, motorbike parking and cleaning are included; no pets. One month deposit, available now.",
  details={"photos": ["assets/fb_photos/1802247057760684/01.webp", "assets/fb_photos/1802247057760684/02.webp", "assets/fb_photos/1802247057760684/03.webp", "assets/fb_photos/1802247057760684/04.webp", "assets/fb_photos/1802247057760684/05.webp"], "notice": "Источник — пост в группе Facebook. Точной даты размещения группа не отдаёт: в данных страницы её нет, а видимые метки времени принадлежат комментариям. Указанный возраст — это время с проверки: 11 сентября 2026 объявление было открыто по ссылке и подтверждено живым. Фотографии взяты из самого поста и хранятся на этом сайте: ссылки Facebook на изображения подписаны и живут около четырёх дней.", "noticeEn": "Source: a post in a Facebook group. The group gives no exact posting date — it is absent from the page data, and the visible timestamps belong to comments. The age shown is time since verification: on 11 September 2026 the listing was opened by its link and confirmed live. The photos come from the post itself and are stored on this site, because Facebook's image links are signed and expire in about four days."}),
L(3000537,"ho-chi-minh","ak","Квартира",17500000,50,
  "1-спальная сервисная квартира 50 м² на ул. Куок Хыонг, Тхао Дьен — гостиная, полностью оборудованная кухня, большая спальня. Обслуживание дома, уборка, смена белья, Wi-Fi и парковка байка включены.",
  "https://www.facebook.com/groups/chungcumini.canhodichvu.phongtrotphcm/posts/1853708945947828/","сегодня",0,source="fbgroup",
  descEn="A 50 m² one-bedroom serviced flat on Quốc Hương street, Thảo Điền — a living room, a fully equipped kitchen and a large bedroom. Building service, cleaning, linen change, WiFi and motorbike parking are included.",
  details={"photos": ["assets/fb_photos/1853708945947828/01.webp", "assets/fb_photos/1853708945947828/02.webp", "assets/fb_photos/1853708945947828/03.webp", "assets/fb_photos/1853708945947828/04.webp", "assets/fb_photos/1853708945947828/05.webp"], "notice": "Источник — пост в группе Facebook. Точной даты размещения группа не отдаёт: в данных страницы её нет, а видимые метки времени принадлежат комментариям. Указанный возраст — это время с проверки: 11 сентября 2026 объявление было открыто по ссылке и подтверждено живым. Фотографии взяты из самого поста и хранятся на этом сайте: ссылки Facebook на изображения подписаны и живут около четырёх дней.", "noticeEn": "Source: a post in a Facebook group. The group gives no exact posting date — it is absent from the page data, and the visible timestamps belong to comments. The age shown is time since verification: on 11 September 2026 the listing was opened by its link and confirmed live. The photos come from the post itself and are stored on this site, because Facebook's image links are signed and expire in about four days."}),
L(3000538,"ho-chi-minh","ak","Квартира",17000000,50,
  "1-спальная квартира 50 м² у дома 204 на ул. Нгуен Ван Хыонг, Тхао Дьен — один санузел. Обслуживание дома, интернет, парковка и уборка раз в неделю включены; можно с кошкой.",
  "https://www.facebook.com/groups/chungcumini.canhodichvu.phongtrotphcm/posts/1801592087826181/","сегодня",0,source="fbgroup",
  descEn="A 50 m² one-bedroom flat near 204 Nguyễn Văn Hưởng street, Thảo Điền — one bathroom. Building service, internet, parking and a weekly clean are included; cats are welcome.",
  details={"photos": ["assets/fb_photos/1801592087826181/01.webp", "assets/fb_photos/1801592087826181/02.webp", "assets/fb_photos/1801592087826181/03.webp", "assets/fb_photos/1801592087826181/04.webp", "assets/fb_photos/1801592087826181/05.webp"], "notice": "Источник — пост в группе Facebook. Точной даты размещения группа не отдаёт: в данных страницы её нет, а видимые метки времени принадлежат комментариям. Указанный возраст — это время с проверки: 11 сентября 2026 объявление было открыто по ссылке и подтверждено живым. Фотографии взяты из самого поста и хранятся на этом сайте: ссылки Facebook на изображения подписаны и живут около четырёх дней.", "noticeEn": "Source: a post in a Facebook group. The group gives no exact posting date — it is absent from the page data, and the visible timestamps belong to comments. The age shown is time since verification: on 11 September 2026 the listing was opened by its link and confirmed live. The photos come from the post itself and are stored on this site, because Facebook's image links are signed and expire in about four days."}),
L(3000539,"nha-trang","tl","Квартира",13000000,None,
  "1-спальная квартира у ул. Нгуен Тхиен Тхуат, центр Нячанга. Депозит месяц, оплата помесячно, договор на 6–12 месяцев; электричество 4 500 ₫ за кВт·ч, вода 120 000 ₫ с человека, интернет 150 000 ₫ и обслуживание 200 000 ₫ в месяц.",
  "https://www.facebook.com/groups/chothuecanhogiarenhatrang/posts/2050739092426859/","сегодня",0,source="fbgroup",
  descEn="A one-bedroom flat near Nguyễn Thiện Thuật street, central Nha Trang. One month deposit, paid monthly, a 6–12 month lease; electricity 4,500 ₫ per kWh, water 120,000 ₫ per person, internet 150,000 ₫ and building service 200,000 ₫ a month.",
  details={"photos": ["assets/fb_photos/2050739092426859/01.webp", "assets/fb_photos/2050739092426859/02.webp", "assets/fb_photos/2050739092426859/03.webp", "assets/fb_photos/2050739092426859/04.webp", "assets/fb_photos/2050739092426859/05.webp"], "notice": "Источник — пост в группе Facebook. Точной даты размещения группа не отдаёт: в данных страницы её нет, а видимые метки времени принадлежат комментариям. Указанный возраст — это время с проверки: 11 сентября 2026 объявление было открыто по ссылке и подтверждено живым. Фотографии взяты из самого поста и хранятся на этом сайте: ссылки Facebook на изображения подписаны и живут около четырёх дней.", "noticeEn": "Source: a post in a Facebook group. The group gives no exact posting date — it is absent from the page data, and the visible timestamps belong to comments. The age shown is time since verification: on 11 September 2026 the listing was opened by its link and confirmed live. The photos come from the post itself and are stored on this site, because Facebook's image links are signed and expire in about four days."}),
L(3000540,"nha-trang","vp","Квартира",12500000,55,
  "2-спальная квартира 55 м² в комплексе Napoleon Castle, Нячанг — один санузел, хорошая меблировка и вся техника; можно с небольшими животными. Договор на год.",
  "https://www.facebook.com/groups/chothuecanhogiarenhatrang/posts/2058946284939473/","сегодня",0,source="fbgroup",
  descEn="A 55 m² two-bedroom flat in the Napoleon Castle complex, Nha Trang — one bathroom, nicely furnished and fully equipped; small pets are welcome. A one-year lease.",
  details={"photos": ["assets/fb_photos/2058946284939473/01.webp", "assets/fb_photos/2058946284939473/02.webp", "assets/fb_photos/2058946284939473/03.webp", "assets/fb_photos/2058946284939473/04.webp", "assets/fb_photos/2058946284939473/05.webp"], "notice": "Источник — пост в группе Facebook. Точной даты размещения группа не отдаёт: в данных страницы её нет, а видимые метки времени принадлежат комментариям. Указанный возраст — это время с проверки: 11 сентября 2026 объявление было открыто по ссылке и подтверждено живым. Фотографии взяты из самого поста и хранятся на этом сайте: ссылки Facebook на изображения подписаны и живут около четырёх дней.", "noticeEn": "Source: a post in a Facebook group. The group gives no exact posting date — it is absent from the page data, and the visible timestamps belong to comments. The age shown is time since verification: on 11 September 2026 the listing was opened by its link and confirmed live. The photos come from the post itself and are stored on this site, because Facebook's image links are signed and expire in about four days."}),
L(3000541,"da-nang","st","Квартира",10000000,None,
  "1-спальная квартира на ул. Хоанг Бить Шон, Шон Ча — диван и телевизор, свой балкон и большие окна, стиральная машина в квартире и общая сушильная машина. Без животных; цена — от 10 млн в месяц.",
  "https://www.facebook.com/groups/canhochothuedanangtot/posts/2203496343611358/","сегодня",0,source="fbgroup",
  descEn="A one-bedroom flat on Hoàng Bích Sơn street, Sơn Trà — a sofa and a TV, a private balcony and large windows, an in-flat washing machine and a shared dryer. No pets; from 10 million a month.",
  details={"photos": ["assets/fb_photos/2203496343611358/01.webp", "assets/fb_photos/2203496343611358/02.webp", "assets/fb_photos/2203496343611358/03.webp", "assets/fb_photos/2203496343611358/04.webp", "assets/fb_photos/2203496343611358/05.webp"], "notice": "Источник — пост в группе Facebook. Точной даты размещения группа не отдаёт: в данных страницы её нет, а видимые метки времени принадлежат комментариям. Указанный возраст — это время с проверки: 11 сентября 2026 объявление было открыто по ссылке и подтверждено живым. Фотографии взяты из самого поста и хранятся на этом сайте: ссылки Facebook на изображения подписаны и живут около четырёх дней.", "noticeEn": "Source: a post in a Facebook group. The group gives no exact posting date — it is absent from the page data, and the visible timestamps belong to comments. The age shown is time since verification: on 11 September 2026 the listing was opened by its link and confirmed live. The photos come from the post itself and are stored on this site, because Facebook's image links are signed and expire in about four days."}),
L(3000542,"da-nang","lc","Квартира",16000000,None,
  "2-спальная квартира в комплексе Mia Centerpoint, ул. Нго Тхи Ням 61, Льен Тьеу — полная меблировка, можно заезжать сразу.",
  "https://www.facebook.com/groups/canhochothuedanangtot/posts/2211064666187859/","сегодня",0,source="fbgroup",
  descEn="A two-bedroom flat in the Mia Centerpoint complex, 61 Ngô Thì Nhậm street, Liên Chiểu — fully furnished and ready to move in.",
  details={"photos": ["assets/fb_photos/2211064666187859/01.webp", "assets/fb_photos/2211064666187859/02.webp", "assets/fb_photos/2211064666187859/03.webp", "assets/fb_photos/2211064666187859/04.webp", "assets/fb_photos/2211064666187859/05.webp"], "notice": "Источник — пост в группе Facebook. Точной даты размещения группа не отдаёт: в данных страницы её нет, а видимые метки времени принадлежат комментариям. Указанный возраст — это время с проверки: 11 сентября 2026 объявление было открыто по ссылке и подтверждено живым. Фотографии взяты из самого поста и хранятся на этом сайте: ссылки Facebook на изображения подписаны и живут около четырёх дней.", "noticeEn": "Source: a post in a Facebook group. The group gives no exact posting date — it is absent from the page data, and the visible timestamps belong to comments. The age shown is time since verification: on 11 September 2026 the listing was opened by its link and confirmed live. The photos come from the post itself and are stored on this site, because Facebook's image links are signed and expire in about four days."}),
L(3000543,"da-nang","st","Студия",11000000,None,
  "Студия с балконом и видом на море на ул. Хоанг Бить Шон, Шон Ча — дом новый, всё в квартире новое, полная меблировка, лифт; свободны квартиры на 4-м и 5-м этажах. До пляжа пешком.",
  "https://www.facebook.com/groups/canhochothuedanangtot/posts/2207115733249419/","сегодня",0,source="fbgroup",
  descEn="A studio with a sea-view balcony on Hoàng Bích Sơn street, Sơn Trà — a brand-new building with everything new inside, fully furnished, with a lift; units on the 4th and 5th floors are available. Walking distance to the beach.",
  details={"photos": ["assets/fb_photos/2207115733249419/01.webp", "assets/fb_photos/2207115733249419/02.webp", "assets/fb_photos/2207115733249419/03.webp", "assets/fb_photos/2207115733249419/04.webp", "assets/fb_photos/2207115733249419/05.webp"], "notice": "Источник — пост в группе Facebook. Точной даты размещения группа не отдаёт: в данных страницы её нет, а видимые метки времени принадлежат комментариям. Указанный возраст — это время с проверки: 11 сентября 2026 объявление было открыто по ссылке и подтверждено живым. Фотографии взяты из самого поста и хранятся на этом сайте: ссылки Facebook на изображения подписаны и живут около четырёх дней.", "noticeEn": "Source: a post in a Facebook group. The group gives no exact posting date — it is absent from the page data, and the visible timestamps belong to comments. The age shown is time since verification: on 11 September 2026 the listing was opened by its link and confirmed live. The photos come from the post itself and are stored on this site, because Facebook's image links are signed and expire in about four days."}),
'''

if __name__ == "__main__":
    insert_listings(NEW_SRC, IDS, owner=__file__)
